// AgentTaskProfile.fsh
// Created: 2026-01-25
// Purpose: Task profile for LLM agent workflow coordination
// Based on: MedAgentBench framework (Saha et al. 2026)
//
// MedAgentBench Tasks:
// - Retrieve patient data
// - Order labs
// - Write clinical notes
// - Generate recommendations
//
// FHIR R4 Task resource used to track agent-initiated clinical workflow items

Profile: AgentTask
Parent: Task
Id: agent-task
Title: "Agent Task Profile"
Description: "Profile for tasks generated by LLM agents. Supports MedAgentBench-style evaluation where agents create actionable clinical workflow items that require human review and execution."

* ^experimental = false

// Core identifiers
* identifier 0..* MS
  * ^short = "Agent-assigned task identifier"
* basedOn 0..* MS
  * ^short = "ServiceRequest or CarePlan this task fulfills"

// Status tracking
* status 1..1 MS
* status from AgentTaskStatusVS (required)
  * ^short = "Current task status (requested | received | accepted | rejected | completed)"

* statusReason 0..1 MS
* statusReason from AgentTaskStatusReasonVS (preferred)
  * ^short = "Reason for current status"

// Business status for agent-specific workflow
* businessStatus 0..1 MS
* businessStatus from AgentTaskBusinessStatusVS (preferred)
  * ^short = "Agent-specific business status"

// Intent must be 'order' or 'proposal' for agent recommendations
* intent 1..1 MS
* intent from AgentTaskIntentVS (required)
  * ^short = "proposal | plan | order"

// Priority based on agent confidence/urgency assessment
* priority 0..1 MS
  * ^short = "Agent-assessed priority"

// Task type - what kind of agent action
* code 1..1 MS
* code from AgentTaskTypeVS (extensible)
  * ^short = "Type of agent task"

// Description with agent reasoning
* description 0..1 MS
  * ^short = "Agent-generated description and reasoning"

// Focus - the resource this task operates on
* focus 0..1 MS
* focus only Reference(Observation or DiagnosticReport or Condition or Patient)
  * ^short = "Resource the task acts upon"

// For - the patient
* for 1..1 MS
* for only Reference(Patient)
  * ^short = "Patient the task is for"

// Encounter context
* encounter 0..1 MS

// Execution period
* executionPeriod 0..1 MS
  * ^short = "When task should be executed"

// Authored date (when agent created)
* authoredOn 1..1 MS
  * ^short = "When agent created this task"

// Last modified
* lastModified 0..1 MS

// Requester - the agent system
* requester 0..1 MS
* requester only Reference(Device or Organization)
  * ^short = "Agent system that created task"

// Owner - clinician responsible
* owner 0..1 MS
* owner only Reference(Practitioner or PractitionerRole or Organization)
  * ^short = "Clinician responsible for task completion"

// Reason code (Task.reasonCode is 0..1 in FHIR R4)
* reasonCode 0..1 MS
* reasonCode from AgentReasonCodeVS (preferred)
  * ^short = "Clinical reason for task"

// Note for additional context
* note 0..* MS
  * ^short = "Additional notes from agent or reviewer"

// Output - result of task completion
* output 0..* MS
  * type MS
  * value[x] MS

// Agent-specific extensions
* extension contains
    AgentRecommendation named agentRecommendation 0..1 MS and
    AgentEvidenceQuality named evidenceQuality 0..1 and
    AgentActionStatus named actionStatus 0..1

// ============================================================================
// Supporting ValueSets
// ============================================================================

ValueSet: AgentTaskStatusVS
Id: agent-task-status-vs
Title: "Agent Task Status ValueSet"
Description: "Allowed status values for agent-created tasks"
* ^experimental = false
* http://hl7.org/fhir/task-status#requested "Requested"
* http://hl7.org/fhir/task-status#received "Received"
* http://hl7.org/fhir/task-status#accepted "Accepted"
* http://hl7.org/fhir/task-status#rejected "Rejected"
* http://hl7.org/fhir/task-status#in-progress "In Progress"
* http://hl7.org/fhir/task-status#completed "Completed"
* http://hl7.org/fhir/task-status#cancelled "Cancelled"

ValueSet: AgentTaskIntentVS
Id: agent-task-intent-vs
Title: "Agent Task Intent ValueSet"
Description: "Intent values for agent tasks"
* ^experimental = false
* http://hl7.org/fhir/request-intent#proposal "Proposal"
* http://hl7.org/fhir/request-intent#plan "Plan"
* http://hl7.org/fhir/request-intent#order "Order"

// ============================================================================
// CodeSystems
// ============================================================================

CodeSystem: AgentTaskTypeCS
Id: agent-task-type-cs
Title: "Agent Task Type CodeSystem"
Description: "Types of tasks that LLM agents can create"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
// Clinical review tasks
* #review-observation "Review Observation" "Agent requests clinician review of an observation"
* #review-trend "Review Trend" "Agent requests clinician review of a data trend"
* #review-alert "Review Alert" "Agent requests clinician review of an alert condition"
// Order-related tasks
* #order-lab "Order Laboratory Test" "Agent recommends laboratory testing"
* #order-imaging "Order Imaging" "Agent recommends imaging study"
* #order-referral "Order Referral" "Agent recommends specialist referral"
// Documentation tasks
* #document-assessment "Document Assessment" "Agent requests clinical documentation"
* #document-care-plan "Update Care Plan" "Agent recommends care plan update"
// Patient communication tasks
* #schedule-followup "Schedule Follow-up" "Agent recommends scheduling patient follow-up"
* #patient-education "Patient Education" "Agent recommends patient education intervention"
* #patient-contact "Patient Contact" "Agent recommends contacting patient"
// Lifestyle intervention tasks
* #lifestyle-exercise "Exercise Intervention" "Agent recommends exercise modification"
* #lifestyle-nutrition "Nutrition Intervention" "Agent recommends dietary modification"
* #lifestyle-sleep "Sleep Intervention" "Agent recommends sleep hygiene intervention"
* #lifestyle-stress "Stress Management" "Agent recommends stress management intervention"

ValueSet: AgentTaskTypeVS
Id: agent-task-type-vs
Title: "Agent Task Type ValueSet"
* ^experimental = false
* include codes from system AgentTaskTypeCS

CodeSystem: AgentTaskBusinessStatusCS
Id: agent-task-business-status-cs
Title: "Agent Task Business Status CodeSystem"
Description: "Business status values specific to agent workflow"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #awaiting-review "Awaiting Review" "Task pending clinician review"
* #under-review "Under Review" "Clinician actively reviewing"
* #approved "Approved" "Clinician approved agent recommendation"
* #modified-approved "Modified and Approved" "Clinician modified and approved"
* #declined "Declined" "Clinician declined recommendation"
* #deferred "Deferred" "Review deferred to later"
* #escalated "Escalated" "Escalated to senior clinician"

ValueSet: AgentTaskBusinessStatusVS
Id: agent-task-business-status-vs
Title: "Agent Task Business Status ValueSet"
* ^experimental = false
* include codes from system AgentTaskBusinessStatusCS

CodeSystem: AgentTaskStatusReasonCS
Id: agent-task-status-reason-cs
Title: "Agent Task Status Reason CodeSystem"
Description: "Reasons for agent task status changes"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #clinician-approved "Clinician Approved" "Clinician reviewed and approved"
* #clinician-rejected "Clinician Rejected" "Clinician reviewed and rejected"
* #insufficient-evidence "Insufficient Evidence" "Rejected due to insufficient evidence"
* #clinical-override "Clinical Override" "Clinician exercised clinical judgment override"
* #patient-declined "Patient Declined" "Patient declined recommended intervention"
* #resources-unavailable "Resources Unavailable" "Required resources not available"
* #superseded "Superseded" "Replaced by newer recommendation"
* #completed-automatically "Completed Automatically" "Task auto-completed by system"

ValueSet: AgentTaskStatusReasonVS
Id: agent-task-status-reason-vs
Title: "Agent Task Status Reason ValueSet"
* ^experimental = false
* include codes from system AgentTaskStatusReasonCS

CodeSystem: AgentReasonCodeCS
Id: agent-reason-code-cs
Title: "Agent Reason Code CodeSystem"
Description: "Clinical reasons for agent-generated tasks"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #abnormal-value "Abnormal Value" "Observation value outside normal range"
* #concerning-trend "Concerning Trend" "Concerning trend in longitudinal data"
* #risk-threshold "Risk Threshold Exceeded" "Risk score exceeded threshold"
* #missing-data "Missing Data" "Required data missing for assessment"
* #routine-followup "Routine Follow-up" "Scheduled routine follow-up"
* #preventive-care "Preventive Care" "Preventive care recommendation"
* #lifestyle-opportunity "Lifestyle Opportunity" "Opportunity for lifestyle improvement"
* #medication-interaction "Medication Interaction" "Potential medication interaction"
* #compliance-concern "Compliance Concern" "Treatment compliance concern"

ValueSet: AgentReasonCodeVS
Id: agent-reason-code-vs
Title: "Agent Reason Code ValueSet"
* ^experimental = false
* include codes from system AgentReasonCodeCS
