// AgentServiceRequestProfile.fsh
// Created: 2026-01-25
// Purpose: ServiceRequest profile for LLM agent clinical recommendations
// Based on: MedAgentBench framework (Saha et al. 2026)
//
// Supports agent-initiated clinical orders and recommendations that require
// clinician authorization before execution.

Profile: AgentServiceRequest
Parent: ServiceRequest
Id: agent-service-request
Title: "Agent Service Request Profile"
Description: "Profile for service requests generated by LLM agents. Captures agent-initiated clinical recommendations (labs, imaging, referrals, interventions) that require clinician authorization."

* ^experimental = false

// Identifiers
* identifier 0..* MS
  * ^short = "Agent-assigned request identifier"

// Instantiates - link to PlanDefinition if applicable
* instantiatesCanonical 0..* MS
  * ^short = "PlanDefinition this request instantiates"

// Based on - link to CarePlan or other ServiceRequest
* basedOn 0..* MS
  * ^short = "Originating CarePlan or parent request"

// Status - tracks authorization workflow
* status 1..1 MS
  * ^short = "draft | active | on-hold | revoked | completed"

// Intent - must indicate agent is proposing/planning
* intent 1..1 MS
* intent from AgentServiceRequestIntentVS (required)
  * ^short = "proposal | plan | directive | order"

// Category - type of service
* category 1..* MS
* category from AgentServiceCategoryVS (extensible)
  * ^short = "Category of service requested"

// Priority
* priority 0..1 MS
  * ^short = "Agent-assessed clinical priority"

// Do not perform flag
* doNotPerform 0..1 MS
  * ^short = "True if agent recommends NOT doing something"

// Code - what is being requested
* code 1..1 MS
* code from AgentServiceCodeVS (extensible)
  * ^short = "What agent is recommending"

// Order detail
* orderDetail 0..* MS
  * ^short = "Additional order details"

// Quantity
* quantity[x] 0..1 MS

// Subject - the patient
* subject 1..1 MS
* subject only Reference(Patient)

// Encounter context
* encounter 0..1 MS

// Occurrence - when should this happen
* occurrence[x] 0..1 MS
  * ^short = "When service should occur"

// As needed
* asNeeded[x] 0..1 MS

// Authored on - when agent created this
* authoredOn 1..1 MS
  * ^short = "When agent generated this request"

// Requester - the agent system
* requester 0..1 MS
* requester only Reference(Device or Organization)
  * ^short = "Agent system that generated request"

// Performer type
* performerType 0..1 MS
  * ^short = "Type of performer needed"

// Performer - who should do it
* performer 0..* MS
  * ^short = "Recommended performer"

// Location
* locationCode 0..* MS
* locationReference 0..* MS

// Reason code - clinical justification
* reasonCode 1..* MS
* reasonCode from AgentReasonCodeVS (preferred)
  * ^short = "Clinical reason for request"

// Reason reference - supporting observations
* reasonReference 0..* MS
* reasonReference only Reference(Observation or Condition or DiagnosticReport)
  * ^short = "Supporting clinical data"

// Supporting info
* supportingInfo 0..* MS
  * ^short = "Additional supporting information"

// Note
* note 0..* MS
  * ^short = "Agent reasoning and notes"

// Patient instruction
* patientInstruction 0..1 MS
  * ^short = "Agent-suggested patient instructions"

// Agent-specific extensions
* extension contains
    AgentRecommendation named agentRecommendation 0..1 MS and
    AgentEvidenceQuality named evidenceQuality 0..1

// ============================================================================
// ValueSets
// ============================================================================

ValueSet: AgentServiceRequestIntentVS
Id: agent-service-request-intent-vs
Title: "Agent Service Request Intent ValueSet"
Description: "Intent values for agent-generated service requests"
* ^experimental = false
* http://hl7.org/fhir/request-intent#proposal "Proposal"
* http://hl7.org/fhir/request-intent#plan "Plan"
* http://hl7.org/fhir/request-intent#directive "Directive"
* http://hl7.org/fhir/request-intent#order "Order"
ValueSet: AgentServiceCategoryVS
Id: agent-service-category-vs
Title: "Agent Service Category ValueSet"
Description: "Categories of services that agents can recommend including diagnostics, consultations, and interventions"
* ^experimental = false
* AgentDecisionSupportCS#order-lab "Order Laboratory Test"
* AgentDecisionSupportCS#order-imaging "Order Imaging"
* AgentDecisionSupportCS#order-referral "Order Referral"
* AgentDecisionSupportCS#lifestyle-exercise "Exercise Intervention"
* AgentDecisionSupportCS#lifestyle-nutrition "Nutrition Intervention"
* AgentDecisionSupportCS#lifestyle-sleep "Sleep Intervention"
* AgentDecisionSupportCS#lifestyle-stress "Stress Management"
ValueSet: AgentServiceCodeVS
Id: agent-service-code-vs
Title: "Agent Service Code ValueSet"
Description: "Specific services that agents can recommend including laboratory tests, cardiac services, and lifestyle interventions"
* ^experimental = false
* AgentDecisionSupportCS#review-observation "Review Observation"
* AgentDecisionSupportCS#review-trend "Review Trend"
* AgentDecisionSupportCS#review-alert "Review Alert"
* AgentDecisionSupportCS#order-lab "Order Laboratory Test"
* AgentDecisionSupportCS#order-imaging "Order Imaging"
* AgentDecisionSupportCS#order-referral "Order Referral"
* AgentDecisionSupportCS#document-assessment "Document Assessment"
* AgentDecisionSupportCS#document-care-plan "Update Care Plan"
* AgentDecisionSupportCS#lifestyle-exercise "Exercise Intervention"
* AgentDecisionSupportCS#lifestyle-nutrition "Nutrition Intervention"
* AgentDecisionSupportCS#lifestyle-sleep "Sleep Intervention"
* AgentDecisionSupportCS#lifestyle-stress "Stress Management"
