// AgentServiceRequestProfile.fsh
// Created: 2026-01-25
// Purpose: ServiceRequest profile for LLM agent clinical recommendations
// Based on: MedAgentBench framework (Saha et al. 2026)
//
// Supports agent-initiated clinical orders and recommendations that require
// clinician authorization before execution.

Profile: AgentServiceRequest
Parent: ServiceRequest
Id: agent-service-request
Title: "Agent Service Request Profile"
Description: "Profile for service requests generated by LLM agents. Captures agent-initiated clinical recommendations (labs, imaging, referrals, interventions) that require clinician authorization."

* ^experimental = false

// Identifiers
* identifier 0..* MS
  * ^short = "Agent-assigned request identifier"

// Instantiates - link to PlanDefinition if applicable
* instantiatesCanonical 0..* MS
  * ^short = "PlanDefinition this request instantiates"

// Based on - link to CarePlan or other ServiceRequest
* basedOn 0..* MS
  * ^short = "Originating CarePlan or parent request"

// Status - tracks authorization workflow
* status 1..1 MS
  * ^short = "draft | active | on-hold | revoked | completed"

// Intent - must indicate agent is proposing/planning
* intent 1..1 MS
* intent from AgentServiceRequestIntentVS (required)
  * ^short = "proposal | plan | directive | order"

// Category - type of service
* category 1..* MS
* category from AgentServiceCategoryVS (extensible)
  * ^short = "Category of service requested"

// Priority
* priority 0..1 MS
  * ^short = "Agent-assessed clinical priority"

// Do not perform flag
* doNotPerform 0..1 MS
  * ^short = "True if agent recommends NOT doing something"

// Code - what is being requested
* code 1..1 MS
* code from AgentServiceCodeVS (extensible)
  * ^short = "What agent is recommending"

// Order detail
* orderDetail 0..* MS
  * ^short = "Additional order details"

// Quantity
* quantity[x] 0..1 MS

// Subject - the patient
* subject 1..1 MS
* subject only Reference(Patient)

// Encounter context
* encounter 0..1 MS

// Occurrence - when should this happen
* occurrence[x] 0..1 MS
  * ^short = "When service should occur"

// As needed
* asNeeded[x] 0..1 MS

// Authored on - when agent created this
* authoredOn 1..1 MS
  * ^short = "When agent generated this request"

// Requester - the agent system
* requester 0..1 MS
* requester only Reference(Device or Organization)
  * ^short = "Agent system that generated request"

// Performer type
* performerType 0..1 MS
  * ^short = "Type of performer needed"

// Performer - who should do it
* performer 0..* MS
  * ^short = "Recommended performer"

// Location
* locationCode 0..* MS
* locationReference 0..* MS

// Reason code - clinical justification
* reasonCode 1..* MS
* reasonCode from AgentReasonCodeVS (preferred)
  * ^short = "Clinical reason for request"

// Reason reference - supporting observations
* reasonReference 0..* MS
* reasonReference only Reference(Observation or Condition or DiagnosticReport)
  * ^short = "Supporting clinical data"

// Supporting info
* supportingInfo 0..* MS
  * ^short = "Additional supporting information"

// Note
* note 0..* MS
  * ^short = "Agent reasoning and notes"

// Patient instruction
* patientInstruction 0..1 MS
  * ^short = "Agent-suggested patient instructions"

// Agent-specific extensions
* extension contains
    AgentRecommendation named agentRecommendation 0..1 MS and
    AgentEvidenceQuality named evidenceQuality 0..1

// ============================================================================
// ValueSets
// ============================================================================

ValueSet: AgentServiceRequestIntentVS
Id: agent-service-request-intent-vs
Title: "Agent Service Request Intent ValueSet"
Description: "Intent values for agent-generated service requests"
* ^experimental = false
* http://hl7.org/fhir/request-intent#proposal "Proposal"
* http://hl7.org/fhir/request-intent#plan "Plan"
* http://hl7.org/fhir/request-intent#directive "Directive"
* http://hl7.org/fhir/request-intent#order "Order"

// ============================================================================
// CodeSystems
// ============================================================================

CodeSystem: AgentServiceCategoryCS
Id: agent-service-category-cs
Title: "Agent Service Category CodeSystem"
Description: "Categories of services that agents can recommend"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
// Diagnostic categories
* #laboratory "Laboratory" "Laboratory testing services"
* #imaging "Imaging" "Imaging and radiology services"
* #cardiac-testing "Cardiac Testing" "Cardiac diagnostic testing"
* #pulmonary-testing "Pulmonary Testing" "Pulmonary function testing"
// Consultation categories
* #specialist-referral "Specialist Referral" "Referral to specialist"
* #mental-health "Mental Health" "Mental health services"
* #nutrition-consult "Nutrition Consultation" "Dietary/nutrition consultation"
* #exercise-physiology "Exercise Physiology" "Exercise physiology consultation"
// Intervention categories
* #lifestyle-intervention "Lifestyle Intervention" "Lifestyle modification intervention"
* #medication-management "Medication Management" "Medication review/management"
* #device-prescription "Device Prescription" "Medical device prescription"
// Monitoring categories
* #remote-monitoring "Remote Monitoring" "Remote patient monitoring setup"
* #wearable-monitoring "Wearable Monitoring" "Consumer wearable monitoring"
// Education categories
* #patient-education "Patient Education" "Patient education services"
* #self-management "Self-Management Support" "Self-management support program"

ValueSet: AgentServiceCategoryVS
Id: agent-service-category-vs
Title: "Agent Service Category ValueSet"
* ^experimental = false
* include codes from system AgentServiceCategoryCS

CodeSystem: AgentServiceCodeCS
Id: agent-service-code-cs
Title: "Agent Service Code CodeSystem"
Description: "Specific services that agents can recommend"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
// Laboratory services
* #cbc "Complete Blood Count" "Recommend CBC panel"
* #cmp "Comprehensive Metabolic Panel" "Recommend CMP"
* #lipid-panel "Lipid Panel" "Recommend lipid panel"
* #hba1c "HbA1c" "Recommend glycated hemoglobin"
* #tsh "Thyroid Function" "Recommend thyroid function testing"
* #crp "C-Reactive Protein" "Recommend inflammatory marker"
* #vitamin-d "Vitamin D Level" "Recommend vitamin D testing"
* #iron-studies "Iron Studies" "Recommend iron studies"
// Cardiac services
* #ecg-12lead "12-Lead ECG" "Recommend standard 12-lead ECG"
* #holter-monitor "Holter Monitor" "Recommend 24-48h Holter monitoring"
* #echo "Echocardiogram" "Recommend echocardiography"
* #stress-test "Stress Test" "Recommend exercise stress testing"
// Lifestyle interventions
* #exercise-prescription "Exercise Prescription" "Recommend structured exercise program"
* #dietary-modification "Dietary Modification" "Recommend dietary changes"
* #sleep-hygiene "Sleep Hygiene Intervention" "Recommend sleep hygiene program"
* #stress-management "Stress Management Program" "Recommend stress management"
* #smoking-cessation "Smoking Cessation" "Recommend smoking cessation support"
* #alcohol-reduction "Alcohol Reduction" "Recommend alcohol reduction program"
// Referrals
* #cardiology-referral "Cardiology Referral" "Refer to cardiology"
* #endocrinology-referral "Endocrinology Referral" "Refer to endocrinology"
* #psychology-referral "Psychology Referral" "Refer to psychology/psychiatry"
* #dietitian-referral "Dietitian Referral" "Refer to registered dietitian"
* #physiotherapy-referral "Physiotherapy Referral" "Refer to physiotherapy"

ValueSet: AgentServiceCodeVS
Id: agent-service-code-vs
Title: "Agent Service Code ValueSet"
* ^experimental = false
* include codes from system AgentServiceCodeCS
