// AgentTaskProfile.fsh
// Created: 2026-01-25
// Purpose: Task profile for LLM agent workflow coordination
// Based on: MedAgentBench framework (Saha et al. 2026)
//
// MedAgentBench Tasks:
// - Retrieve patient data
// - Order labs
// - Write clinical notes
// - Generate recommendations
//
// FHIR R4 Task resource used to track agent-initiated clinical workflow items

Profile: AgentTask
Parent: Task
Id: agent-task
Title: "Agent Task Profile"
Description: "Profile for tasks generated by LLM agents. Supports MedAgentBench-style evaluation where agents create actionable clinical workflow items that require human review and execution."

* ^experimental = false

// Core identifiers
* identifier 0..* MS
  * ^short = "Agent-assigned task identifier"
* basedOn 0..* MS
  * ^short = "ServiceRequest or CarePlan this task fulfills"

// Status tracking
* status 1..1 MS
* status from AgentTaskStatusVS (required)
  * ^short = "Current task status (requested | received | accepted | rejected | completed)"

* statusReason 0..1 MS
* statusReason from AgentTaskStatusReasonVS (preferred)
  * ^short = "Reason for current status"

// Business status for agent-specific workflow
* businessStatus 0..1 MS
* businessStatus from AgentTaskBusinessStatusVS (preferred)
  * ^short = "Agent-specific business status"

// Intent must be 'order' or 'proposal' for agent recommendations
* intent 1..1 MS
* intent from AgentTaskIntentVS (required)
  * ^short = "proposal | plan | order"

// Priority based on agent confidence/urgency assessment
* priority 0..1 MS
  * ^short = "Agent-assessed priority"

// Task type - what kind of agent action
* code 1..1 MS
* code from AgentTaskTypeVS (extensible)
  * ^short = "Type of agent task"

// Description with agent reasoning
* description 0..1 MS
  * ^short = "Agent-generated description and reasoning"

// Focus - the resource this task operates on
* focus 0..1 MS
* focus only Reference(Observation or DiagnosticReport or Condition or Patient)
  * ^short = "Resource the task acts upon"

// For - the patient
* for 1..1 MS
* for only Reference(Patient)
  * ^short = "Patient the task is for"

// Encounter context
* encounter 0..1 MS

// Execution period
* executionPeriod 0..1 MS
  * ^short = "When task should be executed"

// Authored date (when agent created)
* authoredOn 1..1 MS
  * ^short = "When agent created this task"

// Last modified
* lastModified 0..1 MS

// Requester - the agent system
* requester 0..1 MS
* requester only Reference(Device or Organization)
  * ^short = "Agent system that created task"

// Owner - clinician responsible
* owner 0..1 MS
* owner only Reference(Practitioner or PractitionerRole or Organization)
  * ^short = "Clinician responsible for task completion"

// Reason code (Task.reasonCode is 0..1 in FHIR R4)
* reasonCode 0..1 MS
* reasonCode from AgentReasonCodeVS (preferred)
  * ^short = "Clinical reason for task"

// Note for additional context
* note 0..* MS
  * ^short = "Additional notes from agent or reviewer"

// Output - result of task completion
* output 0..* MS
  * type MS
  * value[x] MS

// Agent-specific extensions
* extension contains
    AgentRecommendation named agentRecommendation 0..1 MS and
    AgentEvidenceQuality named evidenceQuality 0..1 and
    AgentActionStatus named actionStatus 0..1

// ============================================================================
// Supporting ValueSets
// ============================================================================

ValueSet: AgentTaskStatusVS
Id: agent-task-status-vs
Title: "Agent Task Status ValueSet"
Description: "Allowed status values for agent-created tasks"
* ^experimental = false
* http://hl7.org/fhir/task-status#requested "Requested"
* http://hl7.org/fhir/task-status#received "Received"
* http://hl7.org/fhir/task-status#accepted "Accepted"
* http://hl7.org/fhir/task-status#rejected "Rejected"
* http://hl7.org/fhir/task-status#in-progress "In Progress"
* http://hl7.org/fhir/task-status#completed "Completed"
* http://hl7.org/fhir/task-status#cancelled "Cancelled"

ValueSet: AgentTaskIntentVS
Id: agent-task-intent-vs
Title: "Agent Task Intent ValueSet"
Description: "Intent values for agent tasks"
* ^experimental = false
* http://hl7.org/fhir/request-intent#proposal "Proposal"
* http://hl7.org/fhir/request-intent#plan "Plan"
* http://hl7.org/fhir/request-intent#order "Order"
ValueSet: AgentTaskTypeVS
Id: agent-task-type-vs
Title: "Agent Task Type ValueSet"
Description: "Types of tasks that LLM agents can create including clinical reviews, orders, documentation, and lifestyle interventions"
* ^experimental = false
* include codes from system LifestyleMedicineTemporaryCS
ValueSet: AgentTaskBusinessStatusVS
Id: agent-task-business-status-vs
Title: "Agent Task Business Status ValueSet"
Description: "Business status values specific to agent workflow including review states and approval outcomes"
* ^experimental = false
* include codes from system LifestyleMedicineTemporaryCS
ValueSet: AgentTaskStatusReasonVS
Id: agent-task-status-reason-vs
Title: "Agent Task Status Reason ValueSet"
Description: "Reasons for agent task status changes including clinician decisions and system events"
* ^experimental = false
* include codes from system LifestyleMedicineTemporaryCS
ValueSet: AgentReasonCodeVS
Id: agent-reason-code-vs
Title: "Agent Reason Code ValueSet"
Description: "Clinical reasons for agent-generated tasks including abnormal values, trends, and care opportunities"
* ^experimental = false
* include codes from system LifestyleMedicineTemporaryCS
