// ============================================================================
// Lifestyle Medicine Temporary CodeSystem (Consolidated)
// ============================================================================
// Generated by scripts/consolidate_codesystems.py
// Consolidation: ~134 domain-specific CodeSystems -> 1 main CS
// 2026-02-27: 100 app-logic codes relocated to AppLogicCS, 1115 -> 1015
// 2026-02-27: 122 agent/CDSS codes relocated (84 to AgentDecisionSupportCS, 38 to CDSS ValueSets), 1015 -> 893
// 2026-02-27: 122 Cat C/D codes relocated to AppLogicCS (app metadata + ordinal scales), 893 -> 771
// 2026-02-27: 21 Cat B Tier 1 codes superseded by standard LOINC/SNOMED/HL7 codes, 771 -> 750
// 2026-02-27: Cat B Tier 2 — 5 ValueSets updated: bulk includes replaced with enumerated SNOMED + custom gap codes (no count change — codes remain in CS, referenced by VS)
// Pattern: Physical Activity IG 'Temporary Codes' (cf. mCODE, US Core)
// Codes are candidates for proposal to LOINC, SNOMED CT, or other standards
//
// CodeSystems kept separate: ICD-11, OMOP, openEHR, vendor APIs,
//   vendor sleep stages, regulatory, practitioner IDs, concept properties

CodeSystem: LifestyleMedicineTemporaryCS
Id: lifestyle-medicine-temporary-cs
Title: "Lifestyle Medicine Temporary Codes"
Description: "Temporary codes for lifestyle medicine concepts not yet covered by standard terminologies (LOINC, SNOMED CT, ICD-11). Following the Physical Activity IG 'Temporary Codes' pattern, these codes are candidates for proposal to standard code systems. Consolidated from domain-specific CodeSystems to align with HL7 FHIR IG best practices (cf. mCODE, PA IG, US Core)."
* ^url = "https://2rdoc.pt/ig/ios-lifestyle-medicine/CodeSystem/lifestyle-medicine-temporary-cs"
* ^version = "0.1.0"
* ^status = #active
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* ^count = 718

// Traceability: codes renamed due to collisions are documented via inline comments.
// Full mapping available in scripts/consolidation_mapping.json


// --- Domain: activity-balance (from ActivityBalanceCS) ---
* #balanced "Well Balanced" "Activity and recovery well balanced"
* #slight-over "Slightly Overtrained" "Slightly more activity than recovery"
* #undertrained "Undertrained" "Less activity than optimal"
* #overtrained "Significantly Overtrained" "Significantly more activity than recovery"

// --- Domain: agent-action-status — RELOCATED to AgentDecisionSupportCS (2026-02-27) ---
// --- 6 codes: pending, accepted, rejected, modified, completed, expired ---

// --- Domain: agent-completeness — RELOCATED to AgentDecisionSupportCS (2026-02-27) ---
// --- 5 codes: complete, mostly-complete, partial, sparse, insufficient ---

// --- Domain: agent-confidence — RELOCATED to AgentDecisionSupportCS (2026-02-27) ---
// --- 5 codes: very-high, high, moderate, low, very-low ---

// --- Domain: agent-interpretation — RELOCATED to AgentDecisionSupportCS (2026-02-27) ---
// --- 15 codes: risk levels, escalation, monitoring, interventions ---

// --- Domain: agent-reason — RELOCATED to AgentDecisionSupportCS (2026-02-27) ---
// --- 9 codes: abnormal-value, concerning-trend, risk-threshold, etc. ---

// --- Domain: agent-service — RELOCATED to ValueSetCDSSLabRecommendations + ValueSetCDSSInterventionRecommendations (2026-02-27) ---
// --- 23 codes replaced with standard LOINC/SNOMED codes ---

// --- Domain: agent-service-cat — RELOCATED to ValueSetCDSSLabRecommendations + ValueSetCDSSInterventionRecommendations (2026-02-27) ---
// --- 15 codes replaced with standard SNOMED codes ---

// --- Domain: agent-task-biz — RELOCATED to AgentDecisionSupportCS (2026-02-27) ---
// --- 7 codes: awaiting-review, under-review, approved, declined, etc. ---

// --- Domain: agent-task-reason — RELOCATED to AgentDecisionSupportCS (2026-02-27) ---
// --- 8 codes: clinician-approved, clinician-rejected, clinical-override, etc. ---

// --- Domain: agent-task-type — RELOCATED to AgentDecisionSupportCS (2026-02-27) ---
// --- 15 codes: review-observation, order-lab, lifestyle-exercise, etc. ---

// --- Domain: agent-topic — RELOCATED to AgentDecisionSupportCS (2026-02-27) ---
// --- 14 codes: cardiovascular-risk, metabolic-risk, hrv-monitoring, etc. ---

// --- Domain: alcohol-freq — SUPERSEDED by standard terminology (2026-02-27) ---
// --- SUPERSEDED by LOINC LA codes (LA6270-8, LA18926-8, LA18927-6, LA18928-4, LA18929-2, LA14435-4) ---
// --- 6 codes: ValueSet updated to use standard codes ---

// --- Domain: alcohol-type (from AlcoholBeverageTypeCS) — PARTIALLY SUPERSEDED (2026-02-27) ---
// SUPERSEDED by SNOMED: beer→53410008, wine→35748005, cider→226025006, fortified-wine→228982004
// KEPT (custom gap): spirits, cocktails — still referenced by AlcoholBeverageTypeVS
* #spirits "Spirits" "Distilled spirits (whiskey, vodka, gin, etc.)"
* #cocktails "Cocktails" "Mixed drinks and cocktails"

// --- Domain: assignment — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 5 codes: mapped, pending-loinc, pending-snomed, local-only, deprecated ---

// --- Domain: assistance-level — RELOCATED to AppLogicCS (Cat D: ordinal scale) (2026-02-27) ---
// --- 5 codes: independent, minimal-assist, moderate-assist, maximal-assist, dependent ---

// --- Domain: audit-formats — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 3 codes: audit-formats-text, structured, audit-formats-mixed ---

// --- Domain: audit-levels — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 3 codes: audit-levels-low, audit-levels-medium, audit-levels-high ---

// --- Domain: balance-status (from BalanceStatusCodeSystem) ---
* #balance-status-normal "Normal"
  // Renamed from BalanceStatusCodeSystem#normal (collision resolution)
* #veryStable "Very Stable"
* #balance-status-stable "Stable"
  // Renamed from BalanceStatusCodeSystem#stable (collision resolution)
* #slightlyUnstable "Slightly Unstable"
* #unstable "Unstable"
* #veryUnstable "Very Unstable"

// --- Domain: baseline — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 3 codes: above, at, below ---

// --- Domain: caffeine-level — RELOCATED to AppLogicCS (Cat D: ordinal scale) (2026-02-27) ---
// --- 5 codes: caffeine-level-none/low/moderate/high, excessive ---

// --- Domain: caffeine-source (from CaffeineSourceCS) ---
* #coffee "Coffee" "Brewed coffee (~95mg per 8oz)"
* #espresso "Espresso" "Espresso (~63mg per shot)"
* #tea "Tea" "Black or green tea (~47mg per 8oz)"
* #energy-drink "Energy drink" "Energy drinks (~80-150mg per can)"
* #soft-drink "Soft drink" "Caffeinated soft drinks (~35mg per 12oz)"
* #chocolate "Chocolate" "Dark chocolate (~23mg per oz)"
* #supplement "Supplement" "Caffeine supplements or pills"
* #pre-workout "Pre-workout" "Pre-workout supplements"

// --- Domain: caregiver (from CaregiverRoleCS) — CONFIRMED CUSTOM GAP (Cat B Tier 3, 2026-02-27) ---
// No SNOMED/LOINC equivalents for caregiving role categories. Candidate for SNOMED proposal.
* #caregiver-not-applicable "Not Applicable" "No caregiving role"
  // Renamed from CaregiverRoleCS#not-applicable (collision resolution)
* #primary-caregiver "Primary Caregiver" "Main caregiver for dependent"
* #secondary-caregiver "Secondary Caregiver" "Shares caregiving responsibilities"
* #care-recipient "Care Recipient" "Receives care from others"
* #mutual-care "Mutual Care" "Both gives and receives care"
* #paid-caregiver "Paid Caregiver" "Professional caregiver"

// --- Domain: cervical-mucus (from CervicalMucusCodeSystem) ---
* #dry "Dry"
* #sticky "Sticky"
* #creamy "Creamy"
* #watery "Watery"
* #eggWhite "Egg White"

// --- Domain: cessation-method (from CessationSupportMethodCS) ---
* #nrt-patch "NRT - Patch" "Nicotine replacement therapy - transdermal patch"
* #nrt-gum "NRT - Gum" "Nicotine replacement therapy - gum"
* #nrt-lozenge "NRT - Lozenge" "Nicotine replacement therapy - lozenge"
* #nrt-inhaler "NRT - Inhaler" "Nicotine replacement therapy - inhaler"
* #varenicline "Varenicline" "Varenicline (Chantix/Champix)"
* #bupropion "Bupropion" "Bupropion (Zyban/Wellbutrin)"
* #counseling "Counseling" "Individual or group counseling"
* #quitline "Quitline" "Telephone quitline support"
* #cessation-method-app "Mobile app" "Cessation support mobile application"
  // Renamed from CessationSupportMethodCS#app (collision resolution)
* #support-group "Support group" "In-person or online support group"
* #acupuncture "Acupuncture" "Acupuncture therapy"
* #hypnotherapy "Hypnotherapy" "Hypnotherapy for cessation"
* #cold-turkey "Cold turkey" "Abrupt cessation without aids"
* #gradual-reduction "Gradual reduction" "Gradual reduction of use"

// --- Domain: cessation-status (from CessationSupportStatusCS) ---
* #considering "Considering" "Considering using this method"
* #scheduled "Scheduled" "Scheduled to start"
* #cessation-status-active "Active" "Currently using this method"
  // Renamed from CessationSupportStatusCS#active (collision resolution)
* #cessation-status-completed "Completed" "Completed this method"
  // Renamed from CessationSupportStatusCS#completed (collision resolution)
* #discontinued "Discontinued" "Stopped using this method"
* #not-interested "Not interested" "Not interested in this method"

// --- Domain: cgm (from CGMMetricsCS) ---
* #cgm-trend "Trend Arrow" "Direction and rate of glucose change"
  // Renamed from CGMMetricsCS#trend (collision resolution)
* #roc "Rate of Change" "Numeric rate of glucose change per minute"
* #tir "Time in Range" "Percentage of time glucose is within target range (70-180 mg/dL)"
* #tbr "Time Below Range" "Percentage of time glucose is below target (<70 mg/dL)"
* #tbr-l1 "Time Below Range Level 1" "Percentage of time in Level 1 hypoglycemia (54-69 mg/dL)"
* #tbr-l2 "Time Below Range Level 2" "Percentage of time in Level 2 hypoglycemia (<54 mg/dL)"
* #tar "Time Above Range" "Percentage of time glucose is above target (>180 mg/dL)"
* #tar-l1 "Time Above Range Level 1" "Percentage of time in Level 1 hyperglycemia (181-250 mg/dL)"
* #tar-l2 "Time Above Range Level 2" "Percentage of time in Level 2 hyperglycemia (>250 mg/dL)"
* #mean "Mean Glucose" "Average glucose over reporting period"
* #sd "Standard Deviation" "Standard deviation of glucose values"
* #cv "Coefficient of Variation" "CV = SD/Mean x 100, target <36%"
* #gmi "Glucose Management Indicator" "Estimated HbA1c from CGM glucose"
* #hypo-events "Hypoglycemia Events" "Number of hypoglycemia episodes"
* #hyper-events "Hyperglycemia Events" "Number of hyperglycemia episodes"
* #cgm-active-time "Sensor Active Time" "Percentage of time sensor was recording"
  // Renamed from CGMMetricsCS#active-time (collision resolution)
* #range-low "Target Range Lower" "Lower bound of target glucose range"
* #range-high "Target Range Upper" "Upper bound of target glucose range"
* #system "CGM System" "Specific CGM device or system"
* #site "Insertion Site" "Body site where sensor is inserted"
* #sensor-days "Sensor Days" "Days since sensor insertion"

// --- Domain: cgm-glucose (from CGMGlucoseInterpretationCS) ---
* #severe-hypo "Severe Hypoglycemia" "<54 mg/dL (<3.0 mmol/L)"
* #hypo "Hypoglycemia" "54-69 mg/dL (3.0-3.8 mmol/L)"
* #in-range "In Range" "70-180 mg/dL (3.9-10.0 mmol/L)"
* #hyper "Hyperglycemia" "181-250 mg/dL (10.1-13.9 mmol/L)"
* #severe-hyper "Severe Hyperglycemia" ">250 mg/dL (>13.9 mmol/L)"

// --- Domain: cgm-site (from CGMInsertionSiteCS) ---
* #upper-arm "Upper Arm" "Back of upper arm"
* #abdomen "Abdomen" "Abdominal area"
* #buttock "Buttock" "Buttock area"
* #thigh "Thigh" "Upper thigh"
* #cgm-site-other "Other" "Other insertion site"
  // Renamed from CGMInsertionSiteCS#other (collision resolution)

// --- Domain: cgm-system — RELOCATED to AppLogicCS (2026-02-27) ---
// 14 codes moved: dexcom-g6, dexcom-g7, dexcom-one, libre-2, libre-3,
// guardian-4, eversense, levels, nutrisense, supersapiens, veri, stelo, lingo,
// cgm-system-other. Reason: device brand names are app-level, not clinical terminology.

// --- Domain: cgm-trend (from CGMTrendArrowCS) ---
* #falling-rapidly "Falling Rapidly" ">3 mg/dL/min downward"
* #falling "Falling" "2-3 mg/dL/min downward"
* #falling-slowly "Falling Slowly" "1-2 mg/dL/min downward"
* #cgm-trend-stable "Stable" "<1 mg/dL/min change"
  // Renamed from CGMTrendArrowCS#stable (collision resolution)
* #rising-slowly "Rising Slowly" "1-2 mg/dL/min upward"
* #rising "Rising" "2-3 mg/dL/min upward"
* #rising-rapidly "Rising Rapidly" ">3 mg/dL/min upward"
* #cgm-trend-unknown "Unknown" "Trend direction not determined"
  // Renamed from CGMTrendArrowCS#unknown (collision resolution)

// --- Domain: circadian (from CircadianPhaseCS) ---
* #early-morning "Early Morning Phase" "Period shortly after awakening"
* #mid-morning "Mid Morning Phase" "Mid-morning period"
* #circadian-afternoon "Afternoon Phase" "Afternoon period"
  // Renamed from CircadianPhaseCS#afternoon (collision resolution)
* #circadian-evening "Evening Phase" "Evening period"
  // Renamed from CircadianPhaseCS#evening (collision resolution)
* #night "Night Phase" "Nighttime period"
* #deep-night "Deep Night Phase" "Deep night period"

// --- Domain: crf-category (from CRFCategoryCS) ---
* #very-poor "Very Poor" "Very poor CRF for age/sex"
* #crf-category-poor "Poor" "Poor CRF for age/sex"
  // Renamed from CRFCategoryCS#poor (collision resolution)
* #below-average "Below Average" "Below average CRF"
* #average "Average" "Average CRF"
* #above-average "Above Average" "Above average CRF"
* #crf-category-good "Good" "Good CRF"
  // Renamed from CRFCategoryCS#good (collision resolution)
* #crf-category-excellent "Excellent" "Excellent CRF"
  // Renamed from CRFCategoryCS#excellent (collision resolution)
* #superior "Superior" "Superior CRF"

// --- Domain: crf-standard (from CRFStandardCS) ---
* #acsm "ACSM" "American College of Sports Medicine"
* #crf-standard-cooper "Cooper Institute" "Cooper Institute norms"
  // Renamed from CRFStandardCS#cooper (collision resolution)
* #hunt "HUNT Fitness Study" "Norwegian HUNT study norms"
* #crf-standard-garmin "Garmin Proprietary" "Garmin proprietary system"
  // Renamed from CRFStandardCS#garmin (collision resolution)
* #crf-standard-apple "Apple Proprietary" "Apple proprietary system"
  // Renamed from CRFStandardCS#apple (collision resolution)
* #crf-standard-polar "Polar Proprietary" "Polar proprietary system"
  // Renamed from CRFStandardCS#polar (collision resolution)
* #crf-standard-other "Other" "Other standard"
  // Renamed from CRFStandardCS#other (collision resolution)

// --- Domain: crp-risk (from HsCRPRiskCS) ---
* #crp-risk-low-risk "Low cardiovascular risk" "hs-CRP < 1.0 mg/L - Low risk of future cardiovascular events"
  // Renamed from HsCRPRiskCS#low-risk (collision resolution)
* #average-risk "Average cardiovascular risk" "hs-CRP 1.0-3.0 mg/L - Intermediate risk requiring lifestyle assessment"
* #crp-risk-high-risk "High cardiovascular risk" "hs-CRP > 3.0 mg/L - High risk warranting intensive intervention"
  // Renamed from HsCRPRiskCS#high-risk (collision resolution)

// --- Domain: cv-risk — RELOCATED to AppLogicCS (Cat D: ordinal scale) (2026-02-27) ---
// --- 4 codes: cv-risk-low/moderate/high/very-high ---

// --- Domain: cycling (from CyclingMetricsCS) ---
* #instant-power "Instantaneous Power" "Current power output in watts"
* #avg-power "Average Power" "Arithmetic mean of power output over the activity"
* #np "Normalized Power" "Weighted average power accounting for variability (Coggan formula)"
* #max-power "Maximum Power" "Peak power achieved during the activity"
* #ftp "Functional Threshold Power" "Highest power sustainable for approximately one hour"
* #power-to-weight "Power-to-Weight Ratio" "Power output relative to body mass (W/kg)"
* #tss "Training Stress Score" "Quantifies training load from power data"
* #if "Intensity Factor" "Ratio of Normalized Power to FTP"
* #ctl "Chronic Training Load" "Long-term training load (fitness)"
* #atl "Acute Training Load" "Short-term training load (fatigue)"
* #tsb "Training Stress Balance" "CTL minus ATL (form)"
* #kj "Kilojoules" "Work performed in kilojoules"
* #cycling-cadence "Cadence" "Current pedaling rate"
  // Renamed from CyclingMetricsCS#cadence (collision resolution)
* #avg-cadence "Average Cadence" "Mean cadence over the activity"
* #lr-balance "Left/Right Power Balance" "Power distribution between legs"
* #avg-speed "Average Speed" "Mean speed over the activity"
* #cycling-elevation "Elevation Gain" "Total vertical meters climbed"
  // Renamed from CyclingMetricsCS#elevation (collision resolution)
* #zone "Training Zone" "Coggan power zone (1-7)"
* #type "Activity Type" "Type of cycling activity"

// --- Domain: cycling-type — RELOCATED to AppLogicCS (2026-02-27) ---
// 8 codes moved: road, mtb, gravel, tt, cycling-type-indoor, virtual, commute, cx.
// --- Domain: cycling-zone — RELOCATED to AppLogicCS (2026-02-27) ---
// 7 codes moved: zone1-zone7. Related LOINC: 74008-4 "Exercise intensity" (broader).

// --- Domain: data-capture — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 5 codes: automatic, manual-entry, derived, synchronized, imported ---

// --- Domain: data-quality — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 4 codes: data-quality-high, data-quality-medium, data-quality-low, data-quality-unreliable ---

// --- Domain: drinking-context (from DrinkingContextCS) ---
* #home-alone "Home alone" "Drinking alone at home"
* #home-social "Home with others" "Drinking at home with family or friends"
* #restaurant "Restaurant/dining" "Drinking with meals at restaurants"
* #bar-club "Bar or club" "Drinking at bars, pubs, or nightclubs"
* #party "Party/celebration" "Drinking at parties or celebrations"
* #work-event "Work event" "Drinking at work-related events"
* #drinking-context-outdoor "Outdoor activity" "Drinking during outdoor activities"
  // Renamed from DrinkingContextCS#outdoor (collision resolution)
* #sporting-event "Sporting event" "Drinking at sporting events"

// --- Domain: ecg (from ECGComponentsCS) ---
* #qt-correction-formula "QT Correction Formula" "Formula used to calculate corrected QT interval"

// --- Domain: environment — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 8 codes: environment-indoor/outdoor/urban/rural/workplace/home, healthcare-facility, environment-recreational ---

// --- Domain: environment-type — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 4 codes: environment-type-indoor/outdoor, quiet, environment-type-group ---

// --- Domain: exercise — RELOCATED to AppLogicCS (2026-02-27) ---
// 9 codes moved: compound-lower/push/pull/full, isolation-lower/upper, exercise-core, olympic, plyometric.

// --- Domain: exposure-conditions — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 4 codes: exposure-conditions-normal/extreme, controlled, app-logic-variable ---

// --- Domain: exposure-location — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 7 codes: exposure-location-indoor/outdoor/workplace, transit, exposure-location-recreational/urban/rural ---

// --- Domain: fall-risk (from FallRiskOutcomes) ---
* #fall-risk-low-risk "Low Risk" "Low risk of falling - minimal intervention needed"
  // Renamed from FallRiskOutcomes#low-risk (collision resolution)
* #fall-risk-moderate-risk "Moderate Risk" "Moderate risk of falling - preventive measures recommended"
  // Renamed from FallRiskOutcomes#moderate-risk (collision resolution)
* #fall-risk-high-risk "High Risk" "High risk of falling - immediate intervention required"
  // Renamed from FallRiskOutcomes#high-risk (collision resolution)
* #fall-occurred "Fall Occurred" "Patient experienced an actual fall event"
* #near-fall "Near Fall" "Patient experienced a near fall event or loss of balance"
* #recurrent-falls "Recurrent Falls" "Patient has history of multiple fall events"
* #fall-with-injury "Fall with Injury" "Fall event resulted in injury"

// --- Domain: family (from FamilyStructureCS) ---
* #household-size "Household size" "Total number of people living in household"
* #dependent-count "Number of dependents" "Number of dependent children or adults"
* #caregiver-role "Caregiver role" "Patient's caregiving responsibilities"
* #relationship-quality "Family relationship quality" "Quality of family relationships"
* #household-type "Household type" "Composition type of household"

// --- Domain: fertility-status (from FertilityStatusCodeSystem) ---
* #fertile "Fertile"
* #notFertile "Not Fertile"
* #fertility-status-uncertain "Uncertain"
  // Renamed from FertilityStatusCodeSystem#uncertain (collision resolution)

// --- Domain: footstrike — RELOCATED to AppLogicCS (2026-02-27) ---
// 4 codes moved: forefoot, midfoot, rearfoot/heel, footstrike-mixed/variable.

// --- Domain: household (from HouseholdTypeCS) — CONFIRMED CUSTOM GAP (Cat B Tier 3, 2026-02-27) ---
// No SNOMED/LOINC equivalents for household composition types. Candidate for SNOMED proposal.
* #single-person "Single Person" "One adult, no children"
* #couple-no-children "Couple Without Children" "Two adults, no children"
* #nuclear-family "Nuclear Family" "Two parents with children"
* #single-parent "Single Parent" "One parent with children"
* #extended-family "Extended Family" "Nuclear family plus other relatives"
* #blended-family "Blended Family" "Step-parents or step-children"
* #household-multigenerational "Multigenerational" "Three or more generations"
  // Renamed from HouseholdTypeCS#multigenerational (collision resolution)
* #shared-housing "Shared Housing" "Unrelated adults sharing residence"
* #group-home "Group Home" "Supervised group living facility"

// --- Domain: hrmax-method (from HRmaxMethodCS) ---
* #measured "Measured" "Directly measured in maximal test"
* #age-220 "220-Age Formula" "Predicted using 220-age"
* #tanaka "Tanaka Formula" "Predicted using 208-0.7*age"
* #hrmax-method-field "Field Observed" "Observed during field activities"
  // Renamed from HRmaxMethodCS#field (collision resolution)
* #hrmax-method-device "Device Learned" "Learned by wearable over time"
  // Renamed from HRmaxMethodCS#device (collision resolution)
* #hrmax-method-unknown "Unknown" "Method unknown"
  // Renamed from HRmaxMethodCS#unknown (collision resolution)

// --- Domain: hrv (from HeartRateVariabilityCS) ---
* #hrv-sdnn "HRV SDNN (Standard Deviation of NN intervals)"
* #hrv-rmssd "HRV RMSSD (Root Mean Square of Successive Differences)"
* #hrv-pnn50 "HRV pNN50 (Percentage of NN intervals >50ms difference)"
* #hrv-lf-hf-ratio "HRV LF/HF Ratio (Low Frequency to High Frequency ratio)"
* #hrv-lf-power "HRV LF Power (Low Frequency power 0.04-0.15 Hz)"
* #hrv-hf-power "HRV HF Power (High Frequency power 0.15-0.4 Hz)"

// --- Domain: injury-risk — RELOCATED to AppLogicCS (Cat D: ordinal scale) (2026-02-27) ---
// --- 4 codes: injury-risk-low/moderate/elevated/high ---

// --- Domain: isolation-factor (from IsolationRiskFactorCS) ---
* #living-alone "Living Alone" "Single-person household"
* #geographic-isolation "Geographic Isolation" "Rural or remote location, limited transport"
* #mobility-impairment "Mobility Impairment" "Physical limitations affecting social participation"
* #recent-relocation "Recent Relocation" "Moved residence within past year"
* #caregiving-burden "Caregiving Burden" "Primary caregiver responsibilities limiting social time"

// --- Domain: isolation-level — RELOCATED to AppLogicCS (Cat D: ordinal scale) (2026-02-27) ---
// --- 5 codes: negligible, isolation-level-low/moderate/high/critical ---

// --- Domain: isolation-method (from IsolationRiskMethodCS) ---
* #lubben-6 "LSNS-6" "Lubben Social Network Scale 6-item (Lubben et al., 2006)"
* #lubben-18 "LSNS-18" "Lubben Social Network Scale 18-item"
* #berkman-sni "Berkman-SNI" "Berkman-Syme Social Network Index"
* #clinical-risk "Clinical Risk Assessment" "Comprehensive clinical assessment of social risk factors"

// --- Domain: isolation-outcome (from IsolationRiskOutcomeCS) ---
* #chronic-isolation "Chronic Social Isolation" "Persistent lack of social contact"
* #severe-loneliness "Severe Loneliness" "Persistent subjective loneliness despite social contact"
* #depression-onset "Depression Onset" "Development of major depressive disorder"
* #cognitive-decline "Cognitive Decline" "Accelerated cognitive deterioration"
* #functional-decline "Functional Decline" "Loss of independent living capacity"

// --- Domain: lifestyle (from LifestyleObservationCS) ---
* #sleep-panel "Sleep measurement panel" "Panel for comprehensive sleep measurements including duration, stages, and quality metrics"
* #noise-avg "Environmental noise average level" "Average environmental noise level measured in decibels (dB) over a specified time period"
* #noise-duration "Environmental noise exposure duration" "Duration of exposure to environmental noise above a threshold level"
* #noise-peak "Peak environmental sound level" "Maximum (peak) environmental sound level measured during a monitoring period"
* #noise-background "Background environmental noise level" "Baseline or background environmental noise level measured in quiet conditions"
* #environmental-audio-exposure "Environmental audio exposure level" "Environmental sound exposure level in A-weighted decibels (dBASPL). Maps to Apple HealthKit HKQuantityTypeIdentifier.environmentalAudioExposure (iOS 13+). WHO recommends <70 dB average over 24h to prevent hearing damage"
* #headphone-audio-exposure "Headphone audio exposure level" "Headphone audio exposure level in A-weighted decibels (dBASPL). Maps to Apple HealthKit HKQuantityTypeIdentifier.headphoneAudioExposure (iOS 14+). WHO recommends <80 dB for max 40 hours/week"
* #sleep-deep "Deep sleep duration" "Duration of deep (slow-wave) sleep stage as measured by consumer sleep tracking device"
* #sleep-light "Light sleep duration" "Duration of light sleep stage as measured by consumer sleep tracking device"
* #rem-sleep "REM sleep duration" "Duration of REM (Rapid Eye Movement) sleep stage as measured by consumer sleep tracking device"
* #sleep-score "Sleep score" "Vendor-specific composite sleep score (0-100) combining duration, efficiency, stages, and HRV during sleep"
* #waso "Wake after sleep onset" "Total time awake after initial sleep onset (WASO). Normal: <30 minutes. Elevated WASO indicates sleep maintenance insomnia"
* #sleep-awakenings "Number of sleep awakenings" "Count of awakenings or sleep interruptions during a sleep period"
* #sleep-time-bed "Time in bed" "Total time spent in bed, including time awake before and after sleep"
* #social-duration "Social interaction duration" "Total duration of social interactions or time spent in social activities"
* #social-quality "Social interaction quality score" "Subjective quality rating of social interactions"
* #social-medium "Social interaction medium" "Method or medium of social interaction (in-person, phone, video, text, etc.)"
* #social-count "Number of social interactions" "Count of distinct social interactions or social contacts during a time period"
* #stress-physiological "Physiological stress indicator" "Physiological markers or indicators of stress response (e.g., heart rate variability, cortisol)"
* #stress-psychological "Psychological stress score" "Self-reported psychological stress level or score from validated assessment"
* #stress-chronicity "Stress chronicity assessment" "Assessment of stress duration and persistence (acute vs. chronic stress)"
* #stress-impact "Stress impact assessment" "Assessment of the impact or severity of stress on daily functioning and health"
* #uv-index "UV index" "Ultraviolet radiation index measurement indicating sun exposure intensity"
* #uv-duration "UV exposure duration" "Duration of exposure to ultraviolet radiation"
* #uv-intensity "UV intensity" "Intensity of ultraviolet radiation exposure"
* #exposure-time "Time of environmental exposure" "Duration of time exposed to a specific environmental condition"
* #hrv-frequency "Heart rate variability frequency band" "Heart rate variability measurement in specific frequency band (LF, HF, VLF)"
* #hrv-entropy "Heart rate variability entropy" "Entropy measurement of heart rate variability indicating complexity"
* #pulse-wave "Pulse wave analysis" "Analysis of arterial pulse wave characteristics"
* #respiratory-variability "Respiratory rate variability" "Variability in respiratory rate over time"
* #oxygenation-index "Oxygenation index" "Calculated index of blood oxygenation efficiency"
* #physiological-stress "Physiological stress index" "Composite index of physiological stress markers"
* #temperature-gradient "Temperature gradient" "Body temperature gradient measurement"
* #autonomic-balance "Autonomic balance index" "Index measuring balance between sympathetic and parasympathetic activity"
* #recovery-rate "Recovery rate index" "Index measuring rate of physiological recovery after activity"
* #allostatic-load "Allostatic load index" "Measure of cumulative physiological burden and wear-and-tear on the body from chronic stress"
* #balance-score "Balance assessment score" "Quantitative score from balance assessment test"
* #balance-assessment "Balance assessment" "Comprehensive balance and stability assessment"
* #balance-status "Balance status" "Qualitative status of balance (normal, impaired, etc.)"
* #gait-assessment "Gait assessment" "Assessment of walking pattern and gait characteristics"
* #movement-assessment "Movement assessment" "General movement quality and mobility assessment"
* #lifestyle-caloric-intake "Total caloric intake" "Total calories consumed in a specified time period"
  // Renamed from LifestyleObservationCS#caloric-intake (collision resolution)
* #macronutrients-panel "Macronutrients intake panel" "Panel for comprehensive macronutrient intake measurements"
* #lifestyle-protein-intake "Protein intake" "Amount of protein consumed"
  // Renamed from LifestyleObservationCS#protein-intake (collision resolution)
* #lifestyle-fat-intake "Fat intake" "Amount of dietary fats consumed"
  // Renamed from LifestyleObservationCS#fat-intake (collision resolution)
* #lifestyle-carbohydrate-intake "Carbohydrate intake" "Amount of carbohydrates consumed"
  // Renamed from LifestyleObservationCS#carbohydrate-intake (collision resolution)
* #ovulation-status "Ovulation status" "Status of ovulation as measured by consumer fertility tracking device"
* #sleep-monitoring-device "Sleep monitoring device" "Device for monitoring and tracking sleep patterns and sleep quality metrics"
* #environmental-sensor "Environmental sensor device" "Device for monitoring environmental conditions such as noise, temperature, humidity, and UV exposure"
* #body-composition-panel "Body composition measurement panel" "Panel for comprehensive body composition measurements from bioimpedance analysis"
* #mindfulness-session "Mindfulness practice session" "A session of mindfulness meditation or practice including breathing exercises, body scans, or mindful awareness"
* #relaxation-response "Relaxation response observation" "Subjective observation of the relaxation response experienced during or after mindfulness or relaxation practice"
* #mindfulness-type "Type of mindfulness practice" "The specific type or technique of mindfulness or meditation practice performed"
* #lifestyle-water-intake "Water intake volume" "Daily water consumption measured in liters or milliliters"
  // Renamed from LifestyleObservationCS#water-intake (collision resolution)
* #walking-speed "Walking speed measurement" "Measurement of walking speed during ambulation"
* #walking-distance "Walking distance measurement" "Measurement of total distance walked"
* #walking-steadiness "Walking steadiness measurement" "Measurement of walking balance and steadiness. Maps to Apple HealthKit HKQuantityTypeIdentifier.appleWalkingSteadiness (iOS 15+)"
* #walking-step-length "Walking step length" "Average step length during walking. Maps to Apple HealthKit HKQuantityTypeIdentifier.walkingStepLength (iOS 14+). Unit: meters"
* #walking-asymmetry "Walking asymmetry percentage" "Percentage difference in step time between left and right legs. Maps to Apple HealthKit HKQuantityTypeIdentifier.walkingAsymmetryPercentage (iOS 14+). Normal: <10%. Values >15% may indicate gait pathology"
* #walking-double-support "Walking double support percentage" "Percentage of gait cycle with both feet on ground. Maps to Apple HealthKit HKQuantityTypeIdentifier.walkingDoubleSupportPercentage (iOS 14+). Increases with age and fall risk"
* #stair-ascent-speed "Stair ascent speed" "Speed of ascending stairs. Maps to Apple HealthKit HKQuantityTypeIdentifier.stairAscentSpeed (iOS 14+). Unit: meters per second. Indicator of lower limb strength and cardiopulmonary function"
* #stair-descent-speed "Stair descent speed" "Speed of descending stairs. Maps to Apple HealthKit HKQuantityTypeIdentifier.stairDescentSpeed (iOS 14+). Unit: meters per second. Relevant for fall risk assessment"
* #six-minute-walk-distance "Six-minute walk test distance" "Distance walked in six minutes. Maps to Apple HealthKit HKQuantityTypeIdentifier.sixMinuteWalkTestDistance (iOS 14+). Unit: meters. Clinical measure of functional exercise capacity"
* #heart-rate-exercise "Heart rate during exercise" "Heart rate measurement during physical exercise activity"
* #heart-rate-variability "Heart rate variability" "Measurement of heart rate variability (HRV)"
* #alcohol-type "Type of alcoholic beverage" "Type of alcoholic beverage consumed (beer, wine, spirits, etc.)"
* #caffeine-source "Caffeine source" "Source of dietary caffeine intake (coffee, tea, energy drinks, etc.)"
* #last-caffeine-time "Time of last caffeine intake" "Date and time of the most recent caffeine consumption"
* #substance-frequency "Frequency of substance use" "How often a substance is used (daily, weekly, monthly, etc.)"
* #last-use-date "Date of last substance use" "Date when a substance was last used"
* #substance-use-summary "Substance use summary" "Comprehensive summary of all substance use patterns for lifestyle medicine assessment"
* #substance-risk-level "Overall substance use risk level" "Aggregate risk assessment based on all substance use patterns"
* #hrv-inflammation-correlation "HRV-Inflammation correlation assessment" "Assessment of the correlation between heart rate variability metrics (especially RMSSD) and inflammatory biomarkers (CRP, IL-6). Based on RS1 systematic review finding: inverse correlation between vagal tone and systemic inflammation via cholinergic anti-inflammatory pathway (Tracey 2002)."

// --- Domain: living (from LivingSituationCS) — PARTIALLY SUPERSEDED (2026-02-27) ---
// SUPERSEDED by SNOMED: alone→105529008, with-spouse→447051007, with-family→224133007, nursing-home→160734000, homeless→160700001
// KEPT (custom gap): living-multigenerational, with-roommates, assisted-living, temporary — still referenced by LivingSituationVS
* #living-multigenerational "Multigenerational" "Three or more generations in household"
  // Renamed from LivingSituationCS#multigenerational (collision resolution)
* #with-roommates "With Roommates" "Non-family cohabitants"
* #assisted-living "Assisted Living" "Assisted living facility"
* #temporary "Temporary Housing" "Transitional or temporary living situation"

// --- Domain: loneliness (from LonelinessComponentCS) ---
* #companionship-lack "Lack of companionship" "How often do you feel that you lack companionship? (UCLA item)"
* #left-out "Feeling left out" "How often do you feel left out? (UCLA item)"
* #isolation "Feeling isolated" "How often do you feel isolated from others? (UCLA item)"
* #no-one-to-talk "No one to talk to" "How often do you feel that there is no one you can turn to? (UCLA item)"
* #not-close-to-anyone "Not close to anyone" "How often do you feel that you are no longer close to anyone? (UCLA item)"

// --- Domain: loneliness-freq (from LonelinessFrequencyCS) ---
* #hardly-ever "Hardly ever" "Rarely or never (score: 1)"
* #some-of-time "Some of the time" "Occasionally (score: 2)"
* #often "Often" "Frequently (score: 3)"

// --- Domain: loneliness-method (from LonelinessAssessmentMethodCS) ---
* #ucla-20 "UCLA Loneliness Scale (20-item)" "Full UCLA Loneliness Scale Version 3 (Russell, 1996)"
* #ucla-3 "UCLA Loneliness Scale (3-item)" "Short form UCLA scale (Hughes et al., 2004)"
* #de-jong "De Jong Gierveld Scale" "De Jong Gierveld Loneliness Scale (11-item)"
* #de-jong-6 "De Jong Gierveld Scale (6-item)" "Short form De Jong Gierveld scale"
* #clinical-interview "Clinical Interview" "Clinical assessment of loneliness"

// --- Domain: measurement-quality — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 5 codes: measurement-quality-excellent/good/fair/poor/unreliable ---

// --- Domain: micronutrient (from MicronutrientCS) ---
* #vitamin-d-intake "Vitamin D intake" "Daily vitamin D intake (IU or mcg)"
* #vitamin-c-intake "Vitamin C intake" "Daily vitamin C intake (mg)"
* #vitamin-a-intake "Vitamin A intake" "Daily vitamin A intake (mcg RAE)"
* #vitamin-e-intake "Vitamin E intake" "Daily vitamin E intake (mg)"
* #vitamin-b12-intake "Vitamin B12 intake" "Daily vitamin B12 intake (mcg)"
* #folate-intake "Folate intake" "Daily folate intake (mcg DFE)"
* #calcium-intake "Calcium intake" "Daily calcium intake (mg)"
* #iron-intake "Iron intake" "Daily iron intake (mg)"
* #micronutrient-sodium-intake "Sodium intake" "Daily sodium intake (mg)"
  // Renamed from MicronutrientCS#sodium-intake (collision resolution)
* #potassium-intake "Potassium intake" "Daily potassium intake (mg)"
* #magnesium-intake "Magnesium intake" "Daily magnesium intake (mg)"
* #zinc-intake "Zinc intake" "Daily zinc intake (mg)"

// --- Domain: mindfulness-outcome (from MindfulnessOutcomeCS) ---
* #increasedAwareness "Increased Awareness" "Greater awareness of thoughts and sensations"
* #improvedFocus "Improved Focus" "Enhanced ability to concentrate"
* #stressReduction "Stress Reduction" "Decreased levels of stress and tension"
* #emotionalBalance "Emotional Balance" "Better emotional regulation"
* #improvedSleep "Improved Sleep" "Enhanced activity quality"

// --- Domain: mindfulness-qualifier (from MindfulnessQualifierCS) ---
* #guided "Guided Practice" "Practice with guidance or instruction"
* #selfDirected "Self-Directed" "Independent practice"
* #mindfulness-qualifier-group "Group Practice" "Practice in group setting"
  // Renamed from MindfulnessQualifierCS#group (collision resolution)
* #individual "Individual Practice" "Solo practice session"

// --- Domain: mindfulness-type (from MindfulnessTypeCS) ---
* #mindfulness-type-meditation "Meditation" "Focused meditation practice"
  // Renamed from MindfulnessTypeCS#meditation (collision resolution)
* #breathing "Breathing Exercise" "Conscious breathing techniques"
* #bodyScan "Body Scan" "Progressive body awareness practice"
* #mindfulness-type-walking "Mindful Walking" "Walking meditation practice"
  // Renamed from MindfulnessTypeCS#walking (collision resolution)
* #movement "Mindful Movement" "Conscious movement practice"

// --- Domain: mindfulness-setting (merged from MindfulnessSettingCS, Phase 4, 2026-02-27) ---
* #mindfulness-setting-home "Home Practice" "Mindfulness practice at home"
* #mindfulness-setting-clinic "Clinical Setting" "Mindfulness practice in a clinical setting"
* #mindfulness-setting-group "Group Setting" "Mindfulness practice in a group setting"
* #mindfulness-setting-retreat "Retreat Setting" "Mindfulness practice at a retreat"
* #mindfulness-setting-workplace "Workplace Setting" "Mindfulness practice in the workplace"

// --- Domain: mobility-alert — SUPERSEDED by standard terminology (2026-02-27) ---
// --- SUPERSEDED by HL7 ObservationInterpretation (N, A, AA) ---
// --- 3 codes: ValueSet updated to use standard codes ---

// --- Domain: mobility-decline (from MobilityDeclineOutcomes) ---
* #no-decline "No Decline" "No mobility decline detected - stable mobility status"
* #mild-decline "Mild Decline" "Mild mobility decline - early changes observed"
* #moderate-decline "Moderate Decline" "Moderate mobility decline - noticeable functional impact"
* #severe-decline "Severe Decline" "Severe mobility decline - significant functional limitation"
* #improved "Improved" "Mobility has improved compared to previous assessment"
* #rapid-decline "Rapid Decline" "Rapid or accelerated mobility decline - urgent attention needed"
* #plateau "Plateau" "Mobility status has plateaued - no significant change"

// --- Domain: mood — SUPERSEDED by standard terminology (2026-02-27) ---
// --- SUPERSEDED by SNOMED CT (247778001, 82248001, 366979004, 38237000, 274646000, 102894008) ---
// --- 6 codes: ValueSet updated to use standard codes ---

// --- Domain: muscle-group — RELOCATED to AppLogicCS (2026-02-27) ---
// 14 codes moved. 13/14 have SNOMED Body Structure equivalents (e.g., quadriceps=21989003).
// ConceptMap to create: AppLogicToSNOMEDBodyStructure.

// --- Domain: nutrition (from NutritionCS) ---
* #nutrition-caloric-intake "Caloric intake" "Total daily energy intake in kcal"
  // Renamed from NutritionCS#caloric-intake (collision resolution)
* #nutrition-protein-intake "Protein intake" "Daily protein intake in grams"
  // Renamed from NutritionCS#protein-intake (collision resolution)
* #nutrition-carbohydrate-intake "Carbohydrate intake" "Daily carbohydrate intake in grams"
  // Renamed from NutritionCS#carbohydrate-intake (collision resolution)
* #nutrition-fat-intake "Fat intake" "Daily total fat intake in grams"
  // Renamed from NutritionCS#fat-intake (collision resolution)
* #fiber-intake "Fiber intake" "Daily dietary fiber intake in grams"
* #saturated-fat "Saturated fat intake" "Daily saturated fat intake in grams"
* #fluid-intake "Fluid intake" "Total daily fluid intake in mL"
* #nutrition-water-intake "Water intake" "Daily water intake in mL"
  // Renamed from NutritionCS#water-intake (collision resolution)
* #nutrition-sodium-intake "Sodium intake" "Daily sodium intake in mg"
  // Renamed from NutritionCS#sodium-intake (collision resolution)
* #diet-quality-score "Diet quality score" "Composite diet quality assessment (e.g., HEI-2020)"
* #meal-frequency "Meal frequency" "Number of meals per day"
* #caffeine-intake "Caffeine intake" "Daily caffeine intake in mg"
* #intermittent-fasting "Intermittent fasting pattern" "Time-restricted eating or fasting pattern"

// --- Domain: nutrition-source — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 4 codes: manual, nutrition-source-app, nutrition-source-device, questionnaire ---

// --- Domain: ovulation-test (from OvulationTestCodeSystem) ---
* #negative "Negative"
* #positive "Positive"
* #invalid "Invalid Test"

// --- Domain: physical-activity (from IOSPhysicalActivityCS) ---
* #physical-activity-walking "Walking" "General walking activity, includes outdoor and indoor walking. Maps to HKWorkoutActivityType.walking."
  // Renamed from IOSPhysicalActivityCS#walking (collision resolution)
* #running "Running" "Running activity, includes outdoor and indoor running. Maps to HKWorkoutActivityType.running."
* #cycling "Cycling" "Cycling activity, includes outdoor and stationary cycling. Maps to HKWorkoutActivityType.cycling."
* #swimming "Swimming" "Swimming activity, includes pool and open water swimming. Maps to HKWorkoutActivityType.swimming."
* #hiking "Hiking" "Hiking activity. Maps to HKWorkoutActivityType.hiking."
* #yoga "Yoga" "Yoga practice. Maps to HKWorkoutActivityType.yoga."
* #dancing "Dancing" "Dancing activity, includes social dance. Maps to HKWorkoutActivityType.dance and HKWorkoutActivityType.socialDance."
* #strength-training "Strength Training" "Traditional strength training with weights. Maps to HKWorkoutActivityType.traditionalStrengthTraining."
* #tennis "Tennis" "Tennis. Maps to HKWorkoutActivityType.tennis."
* #badminton "Badminton" "Badminton. Maps to HKWorkoutActivityType.badminton."
* #squash "Squash" "Squash. Maps to HKWorkoutActivityType.squash."
* #table-tennis "Table Tennis" "Table tennis (ping pong). Maps to HKWorkoutActivityType.tableTennis."
* #soccer "Soccer" "Soccer (football). Maps to HKWorkoutActivityType.soccer."
* #basketball "Basketball" "Basketball. Maps to HKWorkoutActivityType.basketball."
* #volleyball "Volleyball" "Volleyball. Maps to HKWorkoutActivityType.volleyball."
* #tai-chi "Tai Chi" "Tai Chi practice. Maps to HKWorkoutActivityType.taiChi."
* #pilates "Pilates" "Pilates exercise. Maps to HKWorkoutActivityType.pilates."
* #rowing "Rowing" "Rowing activity. Maps to HKWorkoutActivityType.rowing."
* #paddle-sports "Paddle Sports" "Paddle sports including kayaking, canoeing. Maps to HKWorkoutActivityType.paddleSports."
* #skiing "Skiing" "Skiing activity. Maps to HKWorkoutActivityType.downhillSkiing and HKWorkoutActivityType.crossCountrySkiing."
* #snowboarding "Snowboarding" "Snowboarding. Maps to HKWorkoutActivityType.snowboarding."
* #climbing "Climbing" "Climbing activity. Maps to HKWorkoutActivityType.climbing."
* #golf "Golf" "Golf. Maps to HKWorkoutActivityType.golf."
* #elliptical "Elliptical" "Elliptical trainer exercise. Maps to HKWorkoutActivityType.elliptical."
* #stairs "Stairs" "Stair climbing. Maps to HKWorkoutActivityType.stairs and HKWorkoutActivityType.stairStepper."
* #active-minutes "Active Minutes" "Minutes of activity in heart rate zones (moderate to vigorous). Apple: Exercise Ring minutes, Fitbit: Active Zone Minutes, Garmin: Intensity Minutes."
* #met-minutes "MET-Minutes" "Metabolic Equivalent of Task × Duration. Standard measure for physical activity dose. 1 MET = 1 kcal/kg/hour (resting). Target: 500-1000 MET-min/week per guidelines."
* #floors-climbed "Floors Climbed" "Number of floors/flights of stairs climbed. Indicates vertical displacement activity. Typically measured via barometric altimeter."
* #stand-hours "Stand Hours" "Hours with at least 1 minute standing. Apple Watch specific metric. Target: 12 stand hours/day. Proxy for sedentary behavior interruption."

// --- Domain: qt-alert (from QTAlertTypeCS) ---
* #qtc-borderline "QTc Borderline Prolongation" "QTc 440-500ms (men) or 460-500ms (women); warrants monitoring"
* #qtc-prolongation-severe "QTc Severe Prolongation" "QTc >= 500ms; high risk of Torsades de Pointes"
* #qtc-increase-significant "Significant QTc Increase" "QTc increased >60ms from baseline"
* #torsades-warning "Torsades de Pointes Warning" "Pattern suggestive of Torsades de Pointes risk"

// --- Domain: qt-formula (from QTCorrectionFormulaCS) ---
* #bazett "Bazett Formula" "QTc = QT / sqrt(RR). Most widely used; overcorrects at extreme heart rates"
* #fridericia "Fridericia Formula" "QTc = QT / RR^(1/3). Better accuracy during tachycardia"
* #framingham "Framingham Formula" "QTc = QT + 0.154 × (1 - RR). Linear correction approach"
* #hodges "Hodges Formula" "QTc = QT + 1.75 × (HR - 60). Rate-based linear correction"
* #rautaharju "Rautaharju Formula" "Regression-based correction; accounts for sex differences"
* #qt-formula-unknown "Unknown/Not Specified" "Correction method not documented by device"
  // Renamed from QTCorrectionFormulaCS#unknown (collision resolution)

// --- Domain: readiness (from ReadinessCategoryCS) ---
* #optimal "Optimal (85-100)" "Excellent recovery, ready for peak performance"
* #readiness-good "Good (70-84)" "Good recovery, ready for training"
  // Renamed from ReadinessCategoryCS#good (collision resolution)
* #readiness-fair "Fair (50-69)" "Moderate recovery, light activity recommended"
  // Renamed from ReadinessCategoryCS#fair (collision resolution)
* #readiness-low "Low (30-49)" "Low recovery, rest or active recovery"
  // Renamed from ReadinessCategoryCS#low (collision resolution)
* #pay-attention "Pay Attention (<30)" "Very low recovery, focus on rest"

// --- Domain: recommended (from RecommendedActivityCS) ---
* #high-intensity "High Intensity" "Ready for high intensity training"
* #recommended-moderate "Moderate Training" "Ready for moderate intensity"
  // Renamed from RecommendedActivityCS#moderate (collision resolution)
* #recommended-light "Light Activity" "Light activity recommended"
  // Renamed from RecommendedActivityCS#light (collision resolution)
* #active-recovery "Active Recovery" "Active recovery activities"
* #recommended-rest "Rest Day" "Complete rest recommended"
  // Renamed from RecommendedActivityCS#rest (collision resolution)
* #recovery-focus "Recovery Focus" "Focus on recovery activities"

// --- Domain: recovery (from RecoveryMetricsCS) ---
* #readiness "Recovery Readiness Assessment" "Composite recovery and readiness score"
* #recovery-category "Readiness Category" "Categorical interpretation of readiness"
  // Renamed from RecoveryMetricsCS#category (collision resolution)
* #vs-baseline "Compared to Baseline" "How current readiness compares to personal baseline"
* #recovery-trend "Trend Direction" "Direction of readiness trend"
  // Renamed from RecoveryMetricsCS#trend (collision resolution)
* #recovery-oura "Oura Readiness" "Oura Ring readiness score (0-100)"
  // Renamed from RecoveryMetricsCS#oura (collision resolution)
* #recovery-whoop "WHOOP Recovery" "WHOOP recovery percentage (0-100%)"
  // Renamed from RecoveryMetricsCS#whoop (collision resolution)
* #garmin-bb "Garmin Body Battery" "Garmin Body Battery (0-100)"
* #recovery-fitbit "Fitbit Readiness" "Fitbit Daily Readiness Score"
  // Renamed from RecoveryMetricsCS#fitbit (collision resolution)
* #sleep-contrib "Sleep Contribution" "Sleep quality contribution to readiness"
* #hrv-contrib "HRV Contribution" "HRV contribution to readiness"
* #rhr-contrib "Resting HR Contribution" "Resting heart rate contribution"
* #activity-bal "Activity Balance" "Activity balance status"
* #prev-strain "Previous Day Strain" "Strain from previous day"
* #strain-7d "Cumulative Strain 7d" "7-day cumulative strain"
* #debt "Recovery Debt" "Accumulated recovery debt"
* #training-status "Training Status" "Current training status"
* #rec-activity "Recommended Activity" "Recommended activity type"
* #optimal-strain "Optimal Strain" "Optimal strain for today"
* #avg-7d "7-Day Average" "7-day average readiness"
* #avg-30d "30-Day Average" "30-day average readiness"
* #recovery-baseline "Personal Baseline" "Personal baseline readiness"
  // Renamed from RecoveryMetricsCS#baseline (collision resolution)
* #vendor "Primary Vendor" "Primary wearable vendor"

// --- Domain: recovery-debt (from RecoveryDebtCS) ---
* #recovery-debt-none "No Debt" "No accumulated recovery debt"
  // Renamed from RecoveryDebtCS#none (collision resolution)
* #recovery-debt-mild "Mild Debt" "Mild accumulated recovery debt"
  // Renamed from RecoveryDebtCS#mild (collision resolution)
* #recovery-debt-moderate "Moderate Debt" "Moderate accumulated recovery debt"
  // Renamed from RecoveryDebtCS#moderate (collision resolution)
* #significant "Significant Debt" "Significant accumulated recovery debt"

// --- Domain: relationship (from RelationshipQualityCS) ---
* #very-supportive "Very Supportive" "Strong, supportive family relationships"
* #generally-positive "Generally Positive" "Mostly positive relationships with occasional conflict"
* #relationship-mixed "Mixed" "Some positive and some strained relationships"
  // Renamed from RelationshipQualityCS#mixed (collision resolution)
* #strained "Strained" "Predominantly difficult relationships"
* #estranged "Estranged" "No contact with family"
* #relationship-not-applicable "Not Applicable" "No family relationships to assess"
  // Renamed from RelationshipQualityCS#not-applicable (collision resolution)

// --- Domain: reproductive (from ReproductiveActivityCS) ---
* #cycle-tracking "Cycle Tracking" "Track menstrual cycle dates and characteristics"
* #temp-monitoring "Temperature Monitoring" "Monitor basal body temperature"
* #symptom-tracking "Symptom Tracking" "Track social-history health symptoms"
* #vitals-monitoring "Vitals Monitoring" "Monitor vital signs related to social-history health"
* #fertility-signs "Fertility Signs" "Monitor fertility signs and indicators"
* #mood-tracking "Mood Tracking" "Track mood changes related to social-history cycle"
* #medication-log "Medication Log" "Log social-history health medications"
* #exercise-tracking "Exercise Tracking" "Track physical activity during cycle"

// --- Domain: risk-level — RELOCATED to AppLogicCS (Cat D: ordinal scale) (2026-02-27) ---
// --- 6 codes: risk-level-none/low/moderate/high/critical/unknown ---

// --- Domain: running (from RunningMetricsCS) ---
* #gct "Ground Contact Time" "Duration of foot contact with the ground per step"
* #gcb "Ground Contact Balance" "Percentage of ground contact time on the left foot"
* #flight-time "Flight Time" "Time when both feet are off the ground"
* #duty-factor "Duty Factor" "Ground contact time as percentage of stride cycle"
* #vo "Vertical Oscillation" "Vertical bounce during running"
* #vr "Vertical Ratio" "Vertical oscillation relative to stride length"
* #running-cadence "Running Cadence" "Steps per minute during running"
  // Renamed from RunningMetricsCS#cadence (collision resolution)
* #stride "Stride Length" "Distance covered in two steps"
* #step-length "Step Length" "Distance covered in one step"
* #step-variability "Step Rate Variability" "Variability in step timing"
* #running-power "Running Power" "Instantaneous running power in watts"
  // Renamed from RunningMetricsCS#power (collision resolution)
* #form-power "Form Power" "Power used for bouncing/oscillation"
* #fpr "Form Power Ratio" "Form power as percentage of total power"
* #air-power "Air Power" "Power used to overcome air resistance"
* #stiffness "Leg Stiffness" "Spring-like behavior of the leg"
* #v-stiffness "Vertical Stiffness" "Vertical component of leg stiffness"
* #impact "Impact G-forces" "Peak impact force in G-forces"
* #braking "Braking G-forces" "Braking force in G-forces"
* #loading-rate "Impact Loading Rate" "Rate of impact force application"
* #footstrike "Footstrike Type" "Pattern of foot contact with ground"
* #pronation "Pronation Angle" "Inward roll angle of the foot"
* #pace "Pace" "Time per distance unit"
* #running-speed "Average Speed" "Mean speed over the activity"
  // Renamed from RunningMetricsCS#speed (collision resolution)
* #running-elevation "Elevation Gain" "Total elevation climbed"
  // Renamed from RunningMetricsCS#elevation (collision resolution)
* #symmetry "Symmetry Score" "Left-right symmetry percentage"
* #form-score "Form Score" "Overall running form score (0-100)"
* #injury-risk "Injury Risk" "Estimated injury risk based on biomechanics"
* #efficiency "Running Economy" "Oxygen cost per distance at given speed"

// --- Domain: set-type — RELOCATED to AppLogicCS (2026-02-27) ---
// 9 codes moved: warmup, working, top, backoff, drop, rest-pause, cluster, amrap, failure.

// --- Domain: sleep-quality (from SleepQualityCS) ---
* #sleep-quality-excellent "Excellent sleep quality" "Subjective rating of excellent sleep quality. Typically: fell asleep quickly (<15 min), minimal awakenings, felt refreshed upon waking. PSQI equivalent: component score 0."
  // Renamed from SleepQualityCS#excellent (collision resolution)
* #sleep-quality-good "Good sleep quality" "Subjective rating of good sleep quality. Minor issues but overall restorative. PSQI equivalent: component score 1."
  // Renamed from SleepQualityCS#good (collision resolution)
* #sleep-quality-fair "Fair sleep quality" "Subjective rating of fair/moderate sleep quality. Some sleep disturbances but functional. PSQI equivalent: component score 2."
  // Renamed from SleepQualityCS#fair (collision resolution)
* #sleep-quality-poor "Poor sleep quality" "Subjective rating of poor sleep quality. Significant disturbances, not restorative. PSQI equivalent: component score 3."
  // Renamed from SleepQualityCS#poor (collision resolution)
* #restful "Restful sleep" "Sleep characterized by adequate deep sleep and REM stages, low movement, stable heart rate."
* #restless "Restless sleep" "Sleep characterized by frequent movement, elevated heart rate, fragmented stages."
* #interrupted "Interrupted sleep" "Sleep with one or more significant awakenings during the night."
* #uninterrupted "Uninterrupted sleep" "Continuous sleep without significant awakenings."

// --- Domain: social-activity (from SocialActivityCS) ---
* #meal "Shared Meal" "Sharing a meal together"
* #social-activity-exercise "Group Exercise" "Group physical activity"
  // Renamed from SocialActivityCS#exercise (collision resolution)
* #entertainment "Entertainment" "Shared entertainment activity"
* #learning "Learning" "Group learning activity"
* #volunteering "Volunteering" "Community service activity"
* #social-activity-celebration "Celebration" "Social celebration or event"
  // Renamed from SocialActivityCS#celebration (collision resolution)

// --- Domain: social-connection (from SocialConnectionCS) ---
* #loneliness-assessment "Loneliness assessment" "UCLA Loneliness Scale or similar instrument"
* #social-support-assessment "Social support assessment" "MSPSS, MOS-SSS, or similar instrument"
* #family-structure-assessment "Family structure assessment" "Household composition and family relationships"
* #social-isolation-risk "Social isolation risk" "Overall social isolation risk assessment"

// --- Domain: social-context (from SocialContextCS) ---
* #social-context-home "Home" "Home environment"
  // Renamed from SocialContextCS#home (collision resolution)
* #social-context-work "Work" "Work environment"
  // Renamed from SocialContextCS#work (collision resolution)
* #education "Educational" "Educational setting"
* #social-context-community "Community" "Community setting"
  // Renamed from SocialContextCS#community (collision resolution)
* #social-context-recreational "Recreational" "Recreational setting"
  // Renamed from SocialContextCS#recreational (collision resolution)
* #healthcare "Healthcare" "Healthcare setting"

// --- Domain: social-interaction-medium (from SocialInteractionMediumCS) ---
* #inPerson "In Person" "Face-to-face interaction"
* #social-interaction-medium-meaningful "Meaningful" "Deep and significant interaction"
  // Renamed from SocialInteractionMediumCS#meaningful (collision resolution)
* #video "Video Call" "Video-based interaction"
* #voice "Voice Call" "Voice-only interaction"
* #social-interaction-medium-text "Text Based" "Text-based communication"
  // Renamed from SocialInteractionMediumCS#text (collision resolution)
* #social-interaction-medium-social "Social Media" "Social media interaction"
  // Renamed from SocialInteractionMediumCS#social (collision resolution)
* #social-interaction-medium-mixed "Mixed Medium" "Multiple communication methods"
  // Renamed from SocialInteractionMediumCS#mixed (collision resolution)

// --- Domain: social-interaction-quality — RELOCATED to AppLogicCS (Cat D: ordinal scale) (2026-02-27) ---
// --- 5 codes: social-interaction-quality-meaningful, supportive, social-interaction-quality-neutral, superficial, stressful ---

// --- Domain: social-interaction-type (from SocialInteractionTypeCS) ---
* #family "Family Interaction" "Interaction with family members"
* #friends "Friend Interaction" "Interaction with friends"
* #social-interaction-type-professional "Professional Interaction" "Work-related interactions"
  // Renamed from SocialInteractionTypeCS#professional (collision resolution)
* #social-interaction-type-community "Community Interaction" "Community-based interactions"
  // Renamed from SocialInteractionTypeCS#community (collision resolution)
* #social-interaction-type-group "Group Activity" "Organized group activities"
  // Renamed from SocialInteractionTypeCS#group (collision resolution)
* #casual "Casual Interaction" "Casual social encounters"

// --- Domain: social-support — RELOCATED to AppLogicCS (Cat D: ordinal scale) (2026-02-27) ---
// --- 5 codes: strong, adequate, limited, social-support-minimal, social-support-none ---

// --- Domain: social-support-assessment-method (from SocialSupportAssessmentMethodCS) ---
* #mspss "MSPSS" "Multidimensional Scale of Perceived Social Support (Zimet et al., 1988)"
* #duke-unc "Duke-UNC FSSQ" "Duke-UNC Functional Social Support Questionnaire (Broadhead et al., 1988)"
* #mos-sss "MOS-SSS" "Medical Outcomes Study Social Support Survey (Sherbourne & Stewart, 1991)"
* #ssq6 "SSQ6" "Social Support Questionnaire 6-item (Sarason et al., 1987)"
* #isel "ISEL" "Interpersonal Support Evaluation List (Cohen & Hoberman, 1983)"
* #social-support-assessment-method-clinical "Clinical Assessment" "Clinical interview assessment of social support"
  // Renamed from SocialSupportAssessmentMethodCS#clinical (collision resolution)

// --- Domain: social-support-component (from SocialSupportComponentCS) ---
* #total-score "Total support score" "Total social support score across all subscales"
* #family-support "Family support subscale" "MSPSS Family subscale: perceived support from family members"
* #friend-support "Friends support subscale" "MSPSS Friends subscale: perceived support from friends"
* #significant-other-support "Significant other support subscale" "MSPSS Significant Other subscale: perceived support from special person"
* #confidant-support "Confidant support" "Duke-UNC: having someone to confide in"
* #affective-support "Affective support" "Duke-UNC: having someone who shows love and affection"
* #instrumental-support "Instrumental support" "Tangible assistance and practical help"
* #informational-support "Informational support" "Advice, guidance, and information"
* #emotional-support "Emotional support" "Empathy, caring, love, and trust"

// --- Domain: social-support-level — RELOCATED to AppLogicCS (Cat D: ordinal scale) (2026-02-27) ---
// --- 5 codes: social-support-level-very-high/high/moderate/low/very-low ---

// --- Domain: strength (from StrengthTrainingCS) ---
* #exercise-name "Exercise Name" "Name of the exercise performed"
* #strength-category "Exercise Category" "Classification of the exercise type"
  // Renamed from StrengthTrainingCS#category (collision resolution)
* #muscle "Primary Muscle Group" "Main muscle groups targeted"
* #equipment "Equipment Type" "Type of equipment used"
* #set-num "Set Number" "Sequential number of the set"
* #set-type "Set Type" "Classification of the set"
* #reps "Repetitions Performed" "Actual number of repetitions completed"
* #target-reps "Target Repetitions" "Planned number of repetitions"
* #load "Load" "Weight/resistance used for the set"
* #pct-1rm "Percentage of 1RM" "Load expressed as percentage of one repetition maximum"
* #rir "Repetitions in Reserve" "Estimated repetitions remaining before failure"
* #set-rpe "Set RPE" "Rating of Perceived Exertion for the set"
* #strength-rest "Rest Period" "Rest time taken after this set"
  // Renamed from StrengthTrainingCS#rest (collision resolution)
* #tempo "Tempo" "Tempo prescription (e.g., 3-1-2-0)"
* #mean-vel "Mean Concentric Velocity" "Average velocity during the concentric phase"
* #peak-vel "Peak Concentric Velocity" "Maximum velocity achieved during concentric phase"
* #vel-loss "Velocity Loss" "Percentage decrease in velocity from first to last rep"
* #mean-power "Mean Power Output" "Average power generated during the lift"
* #peak-power "Peak Power Output" "Maximum power achieved during the lift"
* #rom "Range of Motion" "Vertical displacement of the bar/implement"
* #tut "Time Under Tension" "Total duration of muscle tension during the set"
* #total-sets "Total Sets" "Total number of working sets performed"
* #total-reps "Total Repetitions" "Sum of all repetitions across all sets"
* #volume-load "Volume Load" "Total volume = sets x reps x load"
* #avg-intensity "Average Intensity" "Mean percentage of 1RM across all working sets"
* #tested-1rm "Tested 1RM" "Directly tested one repetition maximum"
* #est-1rm "Estimated 1RM" "One repetition maximum calculated from submaximal performance"
* #est-method "1RM Estimation Method" "Formula or method used to estimate 1RM"
* #session-rpe "Session RPE" "Overall rating of perceived exertion for the session"
* #session-load "Session Training Load" "Session RPE x duration (sRPE method)"
* #training-type "Training Type" "Primary training goal of the session"
* #split-type "Split Type" "Training split/body part organization"

// --- Domain: strength-equip — RELOCATED to AppLogicCS (2026-02-27) ---
// 11 codes moved. SNOMED: smith=467891002, dumbbell~462529009, cable~464252006.

// --- Domain: strength-type (from StrengthTrainingTypeCS) ---
* #hypertrophy "Hypertrophy" "Muscle growth focus (moderate load, higher volume)"
* #strength "Strength" "Maximal strength focus (high load, lower volume)"
* #strength-type-power "Power" "Explosive power focus (moderate load, high velocity)"
  // Renamed from StrengthTrainingTypeCS#power (collision resolution)
* #endurance "Muscular Endurance" "Endurance focus (lower load, high reps)"
* #fitness "General Fitness" "General conditioning"
* #rehab "Rehabilitation" "Injury rehabilitation or prehab"
* #functional "Functional Training" "Movement-pattern focused training"

// --- Domain: stress-chronicity (from StressChronicityCS) ---
* #acute "Acute" "Short-term stress response"
* #subacute "Subacute" "Medium-term stress response"
* #chronic "Chronic" "Long-term stress response"
* #episodic "Episodic" "Recurring stress episodes"
* #persistent "Persistent" "Continuous stress state"

// --- Domain: stress-coping (from StressCopingCS) ---
* #stress-coping-exercise "Physical Exercise" "Using exercise to manage stress"
  // Renamed from StressCopingCS#exercise (collision resolution)
* #stress-coping-meditation "Meditation" "Meditation and mindfulness practices"
  // Renamed from StressCopingCS#meditation (collision resolution)
* #stress-coping-social "Social Support" "Seeking social support"
  // Renamed from StressCopingCS#social (collision resolution)
* #stress-coping-professional "Professional Help" "Seeking professional assistance"
  // Renamed from StressCopingCS#professional (collision resolution)
* #relaxation "Relaxation" "Relaxation techniques"
* #creative "Creative Activities" "Engaging in creative activities"
* #nature "Nature" "Spending time in nature"

// --- Domain: stress-impact — RELOCATED to AppLogicCS (Cat D: ordinal scale) (2026-02-27) ---
// --- 5 codes: stress-impact-minimal/mild/moderate/severe/extreme ---

// --- Domain: stress-triggers (from StressTriggersCS) ---
* #stress-triggers-work "Work-related" "Stress from work or professional activities"
  // Renamed from StressTriggersCS#work (collision resolution)
* #financial "Financial" "Financial-related stress"
* #relationships "Relationships" "Stress from personal relationships"
* #health "Health" "Health-related concerns"
* #stress-triggers-environment "Environmental" "Environmental factors"
  // Renamed from StressTriggersCS#environment (collision resolution)
* #time "Time Management" "Time pressure and deadlines"
* #stress-triggers-change "Life Changes" "Major life changes or transitions"
  // Renamed from StressTriggersCS#change (collision resolution)

// --- Domain: substance-freq (from SubstanceUseFrequencyCS) ---
* #substance-freq-never "Never" "Never uses this substance"
  // Renamed from SubstanceUseFrequencyCS#never (collision resolution)
* #tried-once "Tried once" "Has tried once but does not use"
* #rarely "Rarely" "Less than once per month"
* #monthly "Monthly" "About once per month"
* #weekly "Weekly" "About once per week"
* #several-times-weekly "Several times weekly" "2-6 times per week"
* #substance-freq-daily "Daily" "Daily use"
  // Renamed from SubstanceUseFrequencyCS#daily (collision resolution)

// --- Domain: substance-motivation — SUPERSEDED by standard terminology (2026-02-27) ---
// --- SUPERSEDED by SNOMED CT (134409004-134414000, Prochaska stages of change) ---
// --- 6 codes: ValueSet updated to use standard codes ---

// --- Domain: substance-risk — RELOCATED to AppLogicCS (Cat D: ordinal scale) (2026-02-27) ---
// --- 5 codes: substance-risk-minimal/low/moderate/high/severe ---

// --- Domain: substance-trigger (from SubstanceUseTriggerCS) ---
* #substance-trigger-stress "Stress" "Work or life stress"
  // Renamed from SubstanceUseTriggerCS#stress (collision resolution)
* #substance-trigger-social "Social situations" "Social gatherings or peer pressure"
  // Renamed from SubstanceUseTriggerCS#social (collision resolution)
* #emotional "Emotional distress" "Anxiety, depression, or emotional pain"
* #boredom "Boredom" "Lack of stimulation or engagement"
* #habit "Habit/routine" "Habitual or routine behavior"
* #substance-trigger-celebration "Celebration" "Celebratory occasions"
  // Renamed from SubstanceUseTriggerCS#celebration (collision resolution)
* #cravings "Physical cravings" "Physical dependency cravings"
* #meals "With meals" "Associated with eating"
* #morning "Morning routine" "Part of morning routine"
* #sleep "Sleep issues" "Difficulty sleeping"
* #pain "Pain" "Physical pain or discomfort"

// --- Domain: substance-type (from RecreationalSubstanceTypeCS) ---
* #opioids "Opioids" "Opioid class substances (heroin, fentanyl, prescription opioids)"
* #benzodiazepines "Benzodiazepines" "Benzodiazepine class (alprazolam, diazepam, etc.)"
* #hallucinogens "Hallucinogens" "Hallucinogenic substances (LSD, psilocybin, etc.)"
* #sedatives "Sedatives" "Sedative/hypnotic class substances"
* #inhalants "Inhalants" "Volatile substances inhaled for effect"
* #synthetic-cannabinoids "Synthetic cannabinoids" "Synthetic cannabinoid receptor agonists"
* #new-psychoactive "New psychoactive substances" "Novel psychoactive substances (NPS)"

// --- Domain: swimming (from SwimmingMetricsCS) ---
* #distance "Total Distance" "Total distance swum in the session"
* #laps "Total Laps" "Total number of pool lengths completed"
* #strokes "Total Strokes" "Total number of strokes in the session"
* #swimming-active-time "Active Swim Time" "Time spent actively swimming"
  // Renamed from SwimmingMetricsCS#active-time (collision resolution)
* #rest-time "Rest Time" "Time spent resting between sets"
* #stroke-type "Primary Stroke Type" "Main stroke type used in the session"
* #strokes-per-lap "Strokes Per Lap" "Average number of strokes per lap"
* #stroke-rate "Stroke Rate" "Number of strokes per minute"
* #dps "Distance Per Stroke" "Average distance traveled per stroke"
* #stroke-index "Stroke Index" "Swimming efficiency metric (speed x DPS)"
* #avg-swolf "Average SWOLF" "Average SWOLF score for the session"
* #best-swolf "Best SWOLF" "Best (lowest) SWOLF score achieved"
* #avg-pace "Average Pace" "Average time per 100 meters"
* #best-pace "Best Pace" "Fastest pace achieved"
* #swimming-speed "Average Speed" "Average swimming speed"
  // Renamed from SwimmingMetricsCS#speed (collision resolution)
* #css "Critical Swim Speed" "Sustainable threshold pace"
* #pool-length "Pool Length" "Length of the pool"
* #swimming-environment "Swimming Environment" "Type of swimming venue"
  // Renamed from SwimmingMetricsCS#environment (collision resolution)
* #max-hr "Maximum Heart Rate" "Maximum heart rate reached during session"
* #aerobic-te "Aerobic Training Effect" "Impact on aerobic fitness (0-5)"
* #anaerobic-te "Anaerobic Training Effect" "Impact on anaerobic capacity (0-5)"
* #training-load "Training Load" "Quantified training stress"

// --- Domain: swimming-env — RELOCATED to AppLogicCS (2026-02-27) ---
// 7 codes moved: pool-25, pool-50, pool-other, ow-lake, ow-ocean, ow-river, endless.

// --- Domain: swimming-stroke (from SwimmingStrokeTypeCS) ---
* #freestyle "Freestyle" "Front crawl stroke"
* #backstroke "Backstroke" "Back crawl stroke"
* #breaststroke "Breaststroke" "Breaststroke technique"
* #butterfly "Butterfly" "Butterfly stroke"
* #im "Individual Medley" "All four strokes in sequence"
* #swimming-stroke-mixed "Mixed/Drill" "Mixed strokes or drill work"
  // Renamed from SwimmingStrokeTypeCS#mixed (collision resolution)
* #swimming-stroke-unknown "Unknown" "Stroke type not detected"
  // Renamed from SwimmingStrokeTypeCS#unknown (collision resolution)

// --- Domain: symptom-freq (from SymptomFrequencyCS) — CONFIRMED CUSTOM GAP (Cat B Tier 3, 2026-02-27) ---
// No standard equivalent for symptom-specific frequency scales. Candidate for LOINC LA proposal.
* #rare "Rare" "Less than once per month"
* #occasional "Occasional" "Several times per month"
* #frequent "Frequent" "Several times per week"
* #symptom-freq-daily "Daily" "Once or more per day"
  // Renamed from SymptomFrequencyCS#daily (collision resolution)
* #constant "Constant" "Present most of the time"

// --- Domain: symptom-impact (from SymptomImpactCS) — CONFIRMED CUSTOM GAP (Cat B Tier 3, 2026-02-27) ---
// No standard equivalent for symptom impact on daily activities. Candidate for LOINC LA proposal.
* #symptom-impact-none "No impact"
  // Renamed from SymptomImpactCS#none (collision resolution)
* #symptom-impact-mild "Mild impact"
  // Renamed from SymptomImpactCS#mild (collision resolution)
* #symptom-impact-moderate "Moderate impact"
  // Renamed from SymptomImpactCS#moderate (collision resolution)
* #symptom-impact-severe "Severe impact"
  // Renamed from SymptomImpactCS#severe (collision resolution)
* #symptom-impact-complete "Complete impact"
  // Renamed from SymptomImpactCS#complete (collision resolution)

// --- Domain: symptom-progression — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 1 code: fluctuating ---

// --- Domain: symptom-severity (from SymptomSeverityCS) — CONFIRMED CUSTOM GAP (Cat B Tier 3, 2026-02-27) ---
// Numeric ranges (1-3, 4-6, 7-8, 9-10) are custom. SNOMED has generic severity but not numeric scales.
* #1-3 "Light" "Symptom barely noticeable"
* #4-6 "Mild" "Symptom noticeable but not interfering with daily activities"
* #7-8 "Intense" "Symptom interfering with daily activities"
* #9-10 "Severe" "Symptom preventing daily activities"

// --- Domain: time-of-day — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 2 codes: time-of-day-evening, time-of-day-afternoon ---

// --- Domain: tobacco-type (from TobaccoProductTypeCS) — PARTIALLY SUPERSEDED (2026-02-27) ---
// SUPERSEDED by SNOMED: cigarette→66562002, cigar→26663004, pipe→84498003, hookah→722495000, e-cig→722498003
// KEPT (custom gap): chewing-tobacco, snuff, heated-tobacco — still referenced by TobaccoProductTypeVS
* #chewing-tobacco "Chewing tobacco" "Smokeless tobacco for chewing"
* #snuff "Snuff" "Nasal snuff"
* #heated-tobacco "Heated tobacco" "Heat-not-burn tobacco products"

// --- Domain: training-status — RELOCATED to AppLogicCS (2026-02-27) ---
// 7 codes moved: peaking, productive, maintaining, training-status-recovery,
// unproductive, detraining, overreaching. Sport science periodisation concepts.

// --- Domain: trend (from TrendDirectionCS) ---
* #trend-improving "Improving" "Readiness is improving"
  // Renamed from TrendDirectionCS#improving (collision resolution)
* #trend-stable "Stable" "Readiness is stable"
  // Renamed from TrendDirectionCS#stable (collision resolution)
* #trend-declining "Declining" "Readiness is declining"
  // Renamed from TrendDirectionCS#declining (collision resolution)

// --- Domain: validation — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 5 codes: validation-clinical, research, manufacturer, not-validated, validation-unknown ---

// --- Domain: vitals-context — RELOCATED to AppLogicCS (Cat C: app metadata) (2026-02-27) ---
// --- 5 codes: resting, vitals-context-active/recovery, activity, vitals-context-stress ---

// --- Domain: vo2max (from VO2maxMetricsCS) ---
* #ci-lower "CI Lower" "Confidence interval lower bound"
* #ci-upper "CI Upper" "Confidence interval upper bound"
* #accuracy "Accuracy" "Estimation accuracy percentage"
* #crf "CRF Category" "Cardiorespiratory fitness category"
* #percentile "Percentile" "Percentile rank"
* #fitness-age "Fitness Age" "Estimated biological age based on CRF"
* #standard "Standard" "Classification standard used"
* #method "Method Type" "Type of estimation method"
* #protocol "Protocol" "Specific test protocol"
* #validation "Validation" "Validation status"
* #rhr-used "RHR Used" "Resting heart rate used"
* #hrmax-used "HRmax Used" "Maximum heart rate used"
* #hrmax-method "HRmax Method" "How HRmax was determined"
* #vo2max-trend "VO2max Trend" "Trend direction over time"
  // Renamed from VO2maxMetricsCS#trend (collision resolution)
* #vo2max-change "Change" "Change from baseline"
  // Renamed from VO2maxMetricsCS#change (collision resolution)
* #pct-change "Percent Change" "Percentage change"
* #vo2max-baseline "Baseline" "Baseline value"
  // Renamed from VO2maxMetricsCS#baseline (collision resolution)
* #cv-risk "CV Risk" "Cardiovascular risk category"
* #mets "METs" "Functional capacity in METs"
* #source "Data Source" "Source of estimation data"

// --- Domain: vo2max-method (from VO2maxMethodCS) ---
* #wearable "Wearable Algorithm" "Algorithm-based from wearable data"
* #submaximal "Submaximal Test" "Submaximal exercise test"
* #non-exercise "Non-Exercise Prediction" "Non-exercise prediction equation"
* #maximal "Maximal Test" "Maximal exercise test"
* #vo2max-method-field "Field Test" "Field-based fitness test"
  // Renamed from VO2maxMethodCS#field (collision resolution)
* #combined "Combined Method" "Multiple combined methods"

// --- Domain: vo2max-protocol (from VO2maxProtocolCS) ---
* #garmin-firstbeat "Garmin FirstBeat" "Garmin FirstBeat analytics"
* #apple-cardio "Apple Cardio Fitness" "Apple Watch algorithm"
* #polar-fitness "Polar Fitness Test" "Polar OwnIndex test"
* #fitbit-cardio "Fitbit Cardio Score" "Fitbit algorithm"
* #vo2max-protocol-coros "COROS" "COROS proprietary"
  // Renamed from VO2maxProtocolCS#coros (collision resolution)
* #vo2max-protocol-suunto "Suunto" "Suunto proprietary"
  // Renamed from VO2maxProtocolCS#suunto (collision resolution)
* #astrand "Astrand-Rhyming" "Astrand-Rhyming cycle test"
* #ymca "YMCA Cycle Test" "YMCA submaximal cycle"
* #rockport "Rockport Walk" "Rockport 1-mile walk test"
* #vo2max-protocol-cooper "Cooper 12-min" "Cooper 12-minute run"
  // Renamed from VO2maxProtocolCS#cooper (collision resolution)
* #6mwt "6-Minute Walk" "Six-minute walk test"
* #uth "Uth Formula" "HRmax/HRrest ratio"
* #bruce "Bruce Treadmill" "Bruce protocol"
* #vo2max-protocol-other "Other" "Other protocol"
  // Renamed from VO2maxProtocolCS#other (collision resolution)

// --- Domain: vo2max-trend (from VO2maxTrendCS) ---
* #sig-improving "Significantly Improving" "Significantly improving"
* #vo2max-trend-improving "Improving" "Improving over time"
  // Renamed from VO2maxTrendCS#improving (collision resolution)
* #vo2max-trend-stable "Stable" "Stable over time"
  // Renamed from VO2maxTrendCS#stable (collision resolution)
* #vo2max-trend-declining "Declining" "Declining over time"
  // Renamed from VO2maxTrendCS#declining (collision resolution)
* #sig-declining "Significantly Declining" "Significantly declining"
* #vo2max-trend-insufficient "Insufficient Data" "Insufficient data for trend"
  // Renamed from VO2maxTrendCS#insufficient (collision resolution)

// --- Domain: warning-type (from ClinicalUseWarningTypeCS) ---
* #consumer-grade-sensor "Consumer-Grade Sensor" "Data derived from consumer-grade sensor (not FDA-cleared for diagnostic use)"
* #algorithm-not-validated "Algorithm Not Validated" "Proprietary algorithm used without published clinical validation"
* #vendor-proprietary "Vendor Proprietary Calculation" "Metric calculated using undisclosed vendor-specific algorithm"
* #insufficient-data-quality "Insufficient Data Quality" "Data quality below threshold for clinical decision-making"
* #single-lead-ecg "Single-Lead ECG Limitation" "ECG data from single-lead device; cannot replace 12-lead clinical ECG"
* #not-fda-cleared-indication "Not FDA-Cleared Indication" "Device not cleared for this specific measurement indication"
* #requires-clinical-correlation "Requires Clinical Correlation" "Value should be correlated with clinical assessment before action"
* #research-use-only "Research Use Only" "Data suitable for research purposes only; not for clinical decisions"

// --- Domain: wearable-device — RELOCATED to AppLogicCS (2026-02-27) ---
// 10 codes moved. pulse-oximeter has SNOMED 448703006 exact match.

// --- Domain: wearable-sensor (from WearableSensorTypeCS) ---
* #ppg "Photoplethysmography (PPG)" "Optical heart rate sensor"
* #ecg "Electrocardiogram (ECG)" "Electrical heart activity sensor"
* #accelerometer "Accelerometer" "Motion and activity sensor"
* #gyroscope "Gyroscope" "Orientation sensor"
* #barometer "Barometer" "Altitude/pressure sensor"
* #spo2 "Pulse Oximeter" "Blood oxygen saturation sensor"
* #temperature "Temperature" "Skin/body temperature sensor"
* #bioimpedance "Bioimpedance" "Body composition sensor"
* #gps "GPS" "Location sensor"

// --- Domain: wearable-vendor (from WearableVendorCS) ---
* #wearable-vendor-oura "Oura" "Oura Ring"
  // Renamed from WearableVendorCS#oura (collision resolution)
* #wearable-vendor-whoop "WHOOP" "WHOOP band"
  // Renamed from WearableVendorCS#whoop (collision resolution)
* #wearable-vendor-garmin "Garmin" "Garmin device"
  // Renamed from WearableVendorCS#garmin (collision resolution)
* #wearable-vendor-polar "Polar" "Polar device"
  // Renamed from WearableVendorCS#polar (collision resolution)
* #wearable-vendor-fitbit "Fitbit" "Fitbit device"
  // Renamed from WearableVendorCS#fitbit (collision resolution)
* #wearable-vendor-apple "Apple" "Apple Watch"
  // Renamed from WearableVendorCS#apple (collision resolution)
* #samsung "Samsung" "Samsung Galaxy Watch"
* #withings "Withings" "Withings device"
* #wearable-vendor-coros "COROS" "COROS watch"
  // Renamed from WearableVendorCS#coros (collision resolution)
* #wearable-vendor-suunto "Suunto" "Suunto watch"
  // Renamed from WearableVendorCS#suunto (collision resolution)
* #wearable-vendor-other "Other" "Other vendor"
  // Renamed from WearableVendorCS#other (collision resolution)

// --- Codes from inline CodeSystems (not originally in consolidation_mapping.json) ---
// These CodeSystems were defined via URL only (not as FSH CodeSystem resources)
// and were missed during initial consolidation.

// From mindfulness-alert-type CodeSystem
* #mindfulness-alert-reminder "Mindfulness Reminder" "Alert type for mindfulness reminders"

// From mindfulness-audit-type CodeSystem
* #mindfulness-audit-session "Session Audit" "Audit type for mindfulness sessions"

// From mindfulness-config-type CodeSystem
* #mindfulness-config-audit "Audit Configuration" "Configuration type for mindfulness auditing"
* #mindfulness-config-settings "Mindfulness Settings" "Configuration type for mindfulness settings"

// From mindfulness-message-events CodeSystem

// From mindfulness-schedule-type CodeSystem
* #mindfulness-schedule-recurring "Recurring Schedule" "Schedule type for recurring mindfulness sessions"

// From mobility-assessment-method CodeSystem
* #mobility-assessment-standardized "Standardized Test" "Standardized mobility assessment method"

